### ISSUE TITLE
ModelBakery Crash

### ISSUE THREAD

**Issue by WenXin20** [GlobbyPotato/Rockhounding_Chemistry#10]
Forge 1.10.2-v2316
Rockhounding Chem v1.41-v1.43
I got this NPE crash after the game launched using these beta versions. 
[Crash Log](https://pastebin.com/1sD8Encg)

**Comment by GlobbyPotato** [comment]
I have no crashes on startup, cannot identify the issue. Is the same in v1.43? Does the mod crashes when on its own? Are you enabling the universal bucket? the only lack of models I can think of are the old beakers removed removed in v1.41.

**Comment by WenXin20** [comment]
I haven't changed any config options. Could it be an id conflict with another mod? I'll try to find out if its another mod causing it.

**Comment by WenXin20** [comment]
It looks like its actually not this mod. I got the crash even with this mod disabled. What's odd is that the crash occurs most of the time, but occasionally it doesn't. Any idea what could cause it?

**Comment by GlobbyPotato** [comment]
if you look in the log folder in the latest log, it should tell exactly at which point the game breaks.
Try also disabling one by one the mods you updated in the latest days,
