### ISSUE TITLE
New reformer CT method is broken

### ISSUE THREAD

**Issue by wormzjl** [GlobbyPotato/Rockhounding_Chemistry#100]
I've tested with the following example script:
`mods.rockhounding_chemistry.GasReformer.add("Cheap Fuel", <liquid:water_vapour>*100, <liquid:oxygen>*150, <liquid:syngas>*110, <minecraft:diamond_sword>);`

However it was not recognized by ct, I got the following error in console:
```
[SERVER_STARTED][SERVER][ERROR] test.zs:1 > a method available but none matches the parameters (string, ZenTypeNative: crafttweaker.liquid.ILiquidStack, ZenTypeNative: crafttweaker.liquid.ILiquidStack, ZenTypeNative: crafttweaker.liquid.ILiquidStack, ZenTypeNative: crafttweaker.item.IItemStack)
This is usually an error in your script, not in the mod
add(ZenTypeNative: crafttweaker.liquid.ILiquidStack, ZenTypeNative: crafttweaker.liquid.ILiquidStack, ZenTypeNative: crafttweaker.liquid.ILiquidStack, ZenTypeNative: crafttweaker.item.IItemStack) 
```

**Comment by wormzjl** [comment]
You've probably forgot to add a `@ZenMethod` before the new method

**Comment by GlobbyPotato** [comment]
hi,
yep, a ZenMethod fell off apparently, probaly accidentally cut on a last minute row managment. The script works now. will put the hotfix soon. Thanks for reporting.
