### ISSUE TITLE
Profiling Bench Animation

### ISSUE THREAD

**Issue by FeedCat02** [GlobbyPotato/Rockhounding_Chemistry#101]
In the latest update the animation for the profiling bench stopped working

**Comment by GlobbyPotato** [comment]
oki, there is definitely something wrong with a specific class, Every fix makes the next call in queue to pop the bug. Will boot the offenders at once, hopefully the rest should not bug.

**Comment by FeedCat02** [comment]
I am assuming if you just load the game and restart it fixes it right?

**Comment by GlobbyPotato** [comment]
Updated the file. If nothing else arises from there, you should see no difference after updating, other than no longer that issue.
