### ISSUE TITLE
Gasification Plant Multiblock Incorrect

### ISSUE THREAD

**Issue by FeedCat02** [GlobbyPotato/Rockhounding_Chemistry#102]
In the manual it shows it needs a gas pressurizer but runs without it. (Also reforming reactor multiblock in the manual shows 4 vessels but says it only requires 3)

**Comment by GlobbyPotato** [comment]
Ah found it, just a check missing.
It's actually 4x vessels. The purging vessel was added later and the book didn't got updated properly.

Thanks.
