### ISSUE TITLE
Miscellaneous Things

### ISSUE THREAD

**Issue by FeedCat02** [GlobbyPotato/Rockhounding_Chemistry#103]
Low density brine shows up in "S" in the fluidpedia
Fullerite shards can be used to make graphite compound and shows when you search for the recipe for graphite compound but when looking at uses of fullerite shards it doesn't show up
Tier 3 and Tier 2 upgrades have their names the wrong way around

Maybe a warning in the book about how much fuel the gasification plant takes to start up

**Comment by GlobbyPotato** [comment]
For the Low Density Brine I can't do much. Fluids are listed by their unlocalized names, which may not reflect the localized ones. In this case it is called "salt_brine" hence listed as S.

Fixed the Fullerite issue. It's a bit of wonkiness in the jei integration of the lab blender. It happens with all the ingredients bypassing oredicts.
Fixed the tiers. I downgraded CuBe to a copper tier desyncing with metadata. No big deal tho.

It is explained in the quest book that you may need several buckets of lava to initially boot the machines. There isn't a precise amount, to avoid confusion. It depends on the temperature you need. Will add an hint to 4-5 buckets just in case.

**Comment by FeedCat02** [comment]
Maybe for the Low density brine you could change the name in the .lang file to something beginning with S.
I started up the gasification plant with 14 blocks of coal or 64 of the Ar.... coal from the ore tiers mod which just seems quite a lot compared to the other machines

**Comment by GlobbyPotato** [comment]
May try to call it Saturated Brine hoping not to fall too off its meaning, but this trick may not work all the times.

Ar should stand for anthracite, right? It should have almost double power than vanilla coal so requiring less. Still I would definitely pump lava and save anthracite for syngas. The initial cost is a matter of mod balancing, considering it's a late game mod. With gasification you can almost immediately create syngas which can be hooked back into any power station for a very cheap fuel and RF. Also having a rotten flesh farm or any of the other mods biofuel/biomass/compost will increase the syngas production. Pretty soon you'll be self-sustained. That's how the mod works.

**Comment by FeedCat02** [comment]
Didn't realise the mod was meant to be end game but you doing a great job.  (Now that I have syngas the gasification burner isn't too much of a hassal)

**Comment by GlobbyPotato** [comment]
It can start early, but the complexity will push it away.
If you have automated canola farming (a must among packs), cracked coal will be history. :)

**Comment by FeedCat02** [comment]
Well it hasn't been too bad when playing alone just having to gather decent amount of iron and redstone is the main thing, the coal is the best bet for syngas as graphite is needed for catalysts to process the minerals
