### ISSUE TITLE
Petrographer Pick & Table Do Not Appear In JEI

### ISSUE THREAD

**Issue by ASolitaryBird** [GlobbyPotato/Rockhounding_Chemistry#105]
Maybe these items were removed (I noticed the Mineral Sizer is now the Miner Controller) but I'm unsure how to begin to process uninspected minerals. Is the guidebook accurate?

**Comment by GlobbyPotato** [comment]
Those tools were in 1.7.10.
In 1.12.2 there is a questbook ingame to explain step by step the processes and a guide book to explain how concepts and machine work

**Comment by ASolitaryBird** [comment]
Excellent, thank you.
