### ISSUE TITLE
Crash when opening UI for Electrochemical CSR

### ISSUE THREAD

**Issue by romiro** [GlobbyPotato/Rockhounding_Chemistry#107]
Trying to create Chloromethane using Nuclearcraft Methanol and Hydrochloric acid (the Dungeons and Dragons and Spaceships modpack), and upon opening the GUI for the main unit, I get the following crash:

https://pastebin.com/tntW8c6w

**Comment by romiro** [comment]
I believe this is from having the two input fluids reversed. I put them in the order that JEI lists and it no longer crashes, but now the machine isn't performing the task.

**Comment by GlobbyPotato** [comment]
Hi, sorry for the delay. Yes, the issue could be due to having the ingredients swapped. I made a fix for this.
I can't see issues with performing the tasks. Do you see the recipe in JEI and does it carry Voltage in RF or is the machine fully assembled?
