### ISSUE TITLE
Crashing after opening CSR GUI

### ISSUE THREAD

**Issue by voidcoefficient** [GlobbyPotato/Rockhounding_Chemistry#109]
I don't think I can give any information that the crash report doesn't give right now, but you can ask me and I could load the world again to check (If you need), or I can just send the world to you. (It's a flat world for testing).

With and without Optifine:
[crash-2019-10-21_00.28.01-client.txt](https://github.com/GlobbyPotato/Rockhounding_Chemistry/files/3748984/crash-2019-10-21_00.28.01-client.txt)
[crash-2019-10-21_00.43.22-client.txt](https://github.com/GlobbyPotato/Rockhounding_Chemistry/files/3748985/crash-2019-10-21_00.43.22-client.txt)

**Comment by GlobbyPotato** [comment]
Hi, sorry for the delay, the issue could be due to having the ingredients added in the wrong order inside the input system. I made a fix to avoid the crash and added an indication to remind the order of the ingredients (primary/secondary) in the tank and JEI
