### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MJRLegends** [GlobbyPotato/Rockhounding_Chemistry#11]
**So in the metal Alloyer it shows items for the recipes,**

as follows
![](https://i.gyazo.com/7796f90e75eb950d9c982893f138a677.png)

but i've turned off the use of that copper powder and i want it to be showing NeoTech copper dust

**any chance you could add a config, like a preferred mod to show recipe inputs items from please**

**also JEI shows the correct item for the one that the player can make**
![](https://i.gyazo.com/740eba862a4b2afd13c12e4c4cb5c021.png)

**Comment by MJRLegends** [comment]
Or would removing all ore dict from each dust/powder im not using stop it from showing?

**Comment by MJRLegends** [comment]
removing all ore dict from each dust/powder fixed it :P

**Comment by GlobbyPotato** [comment]
I can see only part of the original question from the homepage, in case you have concerns with elements dusts you don't want to be produced from here, you can inhibit them from being extracted via CraftTweaker.
If you want to isolate them from being oredicted, yes, removing the oredict will no longer mix the with the other dusts
