### ISSUE TITLE
Mineral Sizer won't crush any material. 

### ISSUE THREAD

**Issue by Dunothar** [GlobbyPotato/Rockhounding_Chemistry#113]

**Comment by Dunothar** [comment]
Need to write a second post because brower messed up something... It seems that the Mineral sizer just will not process any materials. Multiblock should be formed properly, but no matter what I try, it just doesn't work. Everything else from the mod works just fine, just this machine seems to be broken. Running the newest release (also all dependencies) as of today with forge 14.23.3.2689.

**Comment by Dunothar** [comment]
UPDATE: It works with any fuel source in the Power Station. But if you are powering the PS with RF nothing happens, unless you add a burnable fuel. Tested it with all following power generation mods (just one along with JEI, FoamFix and your mod) Mekanism, BuildCraft, ImmersiveEngineering, DraconicEvolution, ActuallyAdditions, ExtremeReactors, Extra Utilities, Matter Overdrive. Nuclearcraft and Thermal Expansion. So it seems that piping in RF doesn't work. All mods where up to date as of today.

**Comment by GlobbyPotato** [comment]
Hi, by default the sizer works on burnables or syngas only. To use RF you need to put in the fuel slot of the power station an Induction Heater Interface to tier-up the power (put a gas turbine in the redstone slot to turn syngas into RF). 
Any machine of the mod requires its own power type (fuel, RF or both). It is indicated in the guidebook next to the power station in the list (in example 1x Power Station (Redstone)) or it is highlited in the gui itself of the power station when correctly assembled.
