### ISSUE TITLE
Methanol cannot be inputted into Reforming Reactor to make Acrylic Acid

### ISSUE THREAD

**Issue by Landmaster** [GlobbyPotato/Rockhounding_Chemistry#116]
Methanol (both native Rockhounding and NuclearCraft) is considered a liquid in the Rockhounding system, but for some reason it's registered in a recipe to make Acrylic Acid in the reformer, even though the reformer is constrained to only take gases as input.

**Comment by GlobbyPotato** [comment]
hi, thanks for reporting. It is a fluid indeed not a gas. It seems a wild recipe remained there unfinished. Will fix it.
