### ISSUE TITLE
Mod packs 

### ISSUE THREAD

**Issue by matthewjessee16** [GlobbyPotato/Rockhounding_Chemistry#117]
Are there any good mod packs for 1.12.2 including the rockhounding mods

**Comment by matthewjessee16** [comment]
Are there

**Comment by gatoborrachon** [comment]
https://www.curseforge.com/minecraft/mc-mods/rockhounding-mod-chemistry/relations/dependents

**Comment by matthewjessee16** [comment]
Are there any with all the rockhounding mods for 1.12.2

**Comment by Filostorm** [comment]
Rockhounding Chemistry plays a big part in my pack, I also created a method to 8x ore process with it.

https://www.curseforge.com/minecraft/modpacks/multiblock-madness

**Comment by Primitive-Human** [comment]
This issue can be closed.
