### ISSUE TITLE
New update and crash loop

### ISSUE THREAD

**Issue by falizure** [GlobbyPotato/Rockhounding_Chemistry#12]
I started updating my modpack today for a Beta server, and i updated chemistry from 1.44 to 1.46, which ment i had to add the core mod, since i was adding that i decided to add the rocks and surfaces mods at the same time, however when starting it up i got this line in the crash report "A dependency cycle was detected in the input mod set so an ordering cannot be determined. The first mod in the cycle is FMLMod:rockhounding_Chemistry(1.10.2-1.46)
I take this to mean chemistry needs the core mod as a dependency however forge has determined that core mod should load "after" chemistry, now i will admit i have little to no experience but that's just my take on it, i will attach the full crash log if that helps.
[crash-2017-07-07_13.15.34-server.txt](https://github.com/GlobbyPotato/Rockhounding_Chemistry/files/1130953/crash-2017-07-07_13.15.34-server.txt)

**Comment by GlobbyPotato** [comment]
It says you have Surfate at v1.15 which has not the core so probably the rockhounding api is conflicting with the one in the core. Try using Surface v1.17.

**Comment by falizure** [comment]
O thank you i missed that, i don't know how i got the wrong version. ill try that.

**Comment by GlobbyPotato** [comment]
no problem, I hope it fixes.

**Comment by falizure** [comment]
That appears to have fixed the issue, thank you for your prompt response as usual, love your work and love your dedication.
