### ISSUE TITLE
 Items getting stuck inside of fluidpedia

### ISSUE THREAD

**Issue by NeuralNotW0rk** [GlobbyPotato/Rockhounding_Chemistry#124]
When I shift-clicked the ampoule in my inventory with the ui open, it placed it inside the machine on top of one of the buttons. I am unable to remove it, and breaking the machine appears to destroy anything inside. Other items can be trapped inside too (as you can see in the image my beloved tinkers hammer somehow ended up inside).
![Untitled2](https://user-images.githubusercontent.com/12944635/82850298-d822dd00-9ec9-11ea-83f7-fcc49378bee3.png)

**Comment by GlobbyPotato** [comment]
Ouch, forgot to update a gui parameter, thanks for reporting, fixed it.
F for hammer
