### ISSUE TITLE
Wrong recipe for ammonia

### ISSUE THREAD

**Issue by whatsapp2** [GlobbyPotato/Rockhounding_Chemistry#125]
Fixed Bed Reactor uses a ratio of 300mB of Nitrogen and 100mB of Hydrogen to make 200mB of Ammonia, this is wrong from a chemical point of view. The correct recipe should be 300mB of Hydrogen and 100mB of Nitrogen

**Comment by GlobbyPotato** [comment]
yep, swapped quantities apparently, still in the testing process. Fixed it, thanks for reporting.
