### ISSUE TITLE
Flotation Tank of Heat Exchanger won't fill automatically

### ISSUE THREAD

**Issue by ChrisEntropy** [GlobbyPotato/Rockhounding_Chemistry#128]
I assembled a heat exchanger with a flotation tank on top, as per guide book. When I connect the flotation tank to a water pump, it is not filled automatically. Filling it with a bucket works, and the heat exchanger will also begin to work, as soon as the flotation tank is filled by hand. The pump is also working, as it fills a fluid container that I connected as a test. Mod Version is: Rockhounding Core 1.12.2-3.22, Rockhounding Chemistry 1.12.2-3.48

**Comment by GlobbyPotato** [comment]
HI, I cannot reproduce the issue, it fills correctly. Is it a specific water pump or pipes or the one in this mod?

**Comment by ChrisEntropy** [comment]
It was the water pump and pipes of the mod. For some reason, the tank seemed to fill after a while, so it was out of sync or not updated correctly I presume. I stopped playing the mod anyway, as it died the lag of death again after I built several gas tanks. I fear that I will never see a full chemistry factory...
