### ISSUE TITLE
Crash when opening GUI for 

### ISSUE THREAD

**Issue by MJRLegends** [GlobbyPotato/Rockhounding_Chemistry#13]
**Description of Issue**
NPE when opening GUI of GAN Controller from Rockhounding Chemistry mod.

**Steps to Reproduce Issue**
1. Place Gan controller
2. Open its GUI

**Crash log/Log (if applicable):**
https://pastebin.com/4TbyP5vK

Rockhounding Core Version: v1.0.5
Rockhounding Chemistry Version: v1.5.1

Reported to me by a player of my pack here: https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/issues/96

**Comment by GlobbyPotato** [comment]
Found it, you put never enough null checks apparently. I will fix it asap.
Meantime, a workaraound can be to put a fluid inside the Heat Exchanget to neutralize the null.
Sorry for the issue.

**Comment by GlobbyPotato** [comment]
The update is now available, it should no longer crash

**Comment by MJRLegends** [comment]
Nice thank you :D
