### ISSUE TITLE
1.14+

### ISSUE THREAD

**Issue by matthewjessee16** [GlobbyPotato/Rockhounding_Chemistry#130]
Can you please port this to newer versions

**Comment by matthewjessee16** [comment]
please

**Comment by gatoborrachon** [comment]
making issues to ask this will do nothing to port it to newer versions, please contribute to this with some Commits and stop doing this in every mod you see

**Comment by matthewjessee16** [comment]
I don’t know how to make commits

**Comment by matthewjessee16** [comment]
If he isn’t willing to update then I’ll do it myself or find someone else who will

**Comment by Primitive-Human** [comment]
This issue can be closed.
