### ISSUE TITLE
Removing Elements Cabinet while Metal Alloyer is in use crashes server

### ISSUE THREAD

**Issue by AnodeCathode** [GlobbyPotato/Rockhounding_Chemistry#131]
With rockhounding_chemistry-1.12.2-3.52.jar  and rockhounding_core-1.12.2-3.22.jar.

Metal Alloyer was processing recipe using only the Materials Cabinet, but when the Elements Cabinet was broken the server crashed.
[
Crash Report](https://pastebin.com/L3MQ5Vkt)

**Comment by GlobbyPotato** [comment]
Sorry for the delay, I think I found the issue, thanks for reporting!
