### ISSUE TITLE
[Crash] Recipes disappearing from JEI Bed Reactor

### ISSUE THREAD

**Issue by gatoborrachon** [GlobbyPotato/Rockhounding_Chemistry#132]
when i check the recipes of the fixed bed reactor, everytime i check the functions of nitrogen (from Galacticraft) the game hides a recipe from this machine (fixed bed reactor) and only this machine, and when you do it 2 times the game crash with this issue:
https://pastebin.com/ymejqngN

i tested NuclearCraft 1 day ago and the fixed bed reactor was using the nitrogen from NC, it seemed to not be any issue, also using Galacticraft's nitrogen doesn't crash or hide any othe recipe from the other machines

**Comment by GlobbyPotato** [comment]
Hi, found it, it's a JEI compat issue in recipes where an ingredient is not used, it should be fine now, will update soon. Thanks for reporting

**Comment by gatoborrachon** [comment]
ok, i'm closing the issue
