### ISSUE TITLE
Toxic Waste Crash (1.12.2) 

### ISSUE THREAD

**Issue by AnodeCathode** [GlobbyPotato/Rockhounding_Chemistry#133]
When toxic waste attempts to spill with a machine powered with an IE connector:

https://pastebin.com/BjVKR7TV

Mods: 
rockhounding_chemistry-1.12.2-3.52
rockhounding_core-1.12.2-3.22
immersiveengineering-0.12-98

**Comment by GlobbyPotato** [comment]
Hi, not sure how to reproduce the issue using IE, a screenshot before the crash would help

**Comment by Broam** [comment]
This was with a Reforming Reactor.

An IE LV connector was connected to the "back" of the Power Station (where Syngas is accepted). When the buffer tank overflowed, the pollution attempted to spawn right in the same block as the connector, and crash.

I worked around this by using XNet to pipe in RF power from the bottom of the Power Station.

**Comment by GlobbyPotato** [comment]
Thanks, will give it a check, it shouldn't attempt to leak on a non-air block.
