### ISSUE TITLE
[Issue] Containment Tank is not accepting pollutants added via Crafttweaker

### ISSUE THREAD

**Issue by gatoborrachon** [GlobbyPotato/Rockhounding_Chemistry#134]
I added <liquid:oil> as a new fluid pollutant, JEI recognize it and Crafttweaker does not throw any error when you start a world, but anyways i can't put oil into a containment tank

code line added via ZenScript: `mods.rockhounding_chemistry.PollutantFluids.pollute(<liquid:oil>*1000); `

Video: https://streamable.com/dblbj1

Rockhounding mod: Chemistry version: 3.52

**Comment by GlobbyPotato** [comment]
Please give a look into the Fluidpedia. Unless there is any bug somewhere, if the oil is marked as "Heavy Fluid" it must be contained inside the Heavy Drum. The fluid tank and the containment tank only accept "Light Fluids". The difference is a calculation between density and viscosity, you can find it somewhere in the guide book. This is a feature of the mod for balancing and :cough:realism:cough: reasons

**Comment by gatoborrachon** [comment]
yeah i like that realism essence, it's perfect for my personal "modpack" if i can name it like that, and the oil can be stored in the Heavy Drum, i'm closing the issue now
