### ISSUE TITLE
[Issue] Crash everytime that the Chemical Extractor process a shard

### ISSUE THREAD

**Issue by gatoborrachon** [GlobbyPotato/Rockhounding_Chemistry#135]
as the title says, when the Chemical Extractor process a shard, the game crashes, but when i re-enter the world the cabinets have their respective dust processed, VanillaFix told me that HammerCore is involucred
(tell me if i need to open an issue in HammerCore issue tracker)

https://pastebin.com/wFEAHxPZ

Rockhounding mod: Chemistry version: 3.53
Rockhounding mod: Core version: 3.23
HammerCore version: 2.0.6.23

**Comment by GlobbyPotato** [comment]
I don't think HammerCore is involved, but that type of error happens if the Chemistry module is not recognizing the latest Core, because it is calling a method I added in the latest version 3.23. Do you have a double in your folders?

**Comment by GlobbyPotato** [comment]
ok I think you are right, there was a discrepancy in the compiled jar. for some reason there was a wrong class on it. Just uploaded version 3.24 of the Core. It should solve the crash. Let me know if it persists.
Sorry for the issue.

**Comment by AnodeCathode** [comment]
Thanks, just came to report the same issue. Will await the update to RH Core.

**Comment by gatoborrachon** [comment]
yeah it works, sorry for late reply
