### ISSUE TITLE
Low Grade Leachate / High Grade Leachate are not Pollutant Fluids

### ISSUE THREAD

**Issue by AnodeCathode** [GlobbyPotato/Rockhounding_Chemistry#138]
With rockhounding_chemistry-1.12.2-3.54 and the new grades of leachate. Only the original medium grade leachate is a pollutant fluid. Intended?

**Comment by GlobbyPotato** [comment]
Hi, actually not intended, just forgot that step. Still working on using them so will fix it when possible. Meantime you can add it manually with CraftTweaker:
`mods.rockhounding_chemistry.PollutantFluid.add(<liquid:high_leachate>*1000);`
`mods.rockhounding_chemistry.PollutantFluid.add(<liquid:low_leachate>*1000);`
