### ISSUE TITLE
Request: Allow Mineral Sizer to accept higher levels of Unbreaking.

### ISSUE THREAD

**Issue by Filostorm** [GlobbyPotato/Rockhounding_Chemistry#139]
I'm working on a pack, and one of the things I'm adding is the ability to craft Crushing Gears with unbreaking 1-4. However, if I try to increase the level of unbreaking past that it crashes the server while in the machine. [Crash Log.](https://pastebin.com/LNxP4hcF)

I'm guessing this is also the case for Slurry Agitators, but I haven't tested.

Alternately would it be possible to allow for multiple types of Crushing Gears that all have different durabilities?

**Comment by GlobbyPotato** [comment]
Hi, I made a fix that should allow higher values of Unbreaking to be accounted.
Also added the chance to set via CrafTweaker any damageable item to the Mineral Sizer. See the script [HERE](https://github.com/GlobbyPotato/Rockhounding_Chemistry/blob/337bb9aa23e0f03185b9c40bdba3be125d9c80c2/CraftTweaker_chemistry_script_1_12_2.zs#L64-L68). Doing it only for the Sizer as it has common items, though the ones with no durability will not be considered valid. Let me know if all works eventually.
Thanks for reporting.

**Comment by Filostorm** [comment]
This is perfect, thank you so much! Love your mod by the way.

**Comment by Filostorm** [comment]
Works perfectly: [Gears added](https://imgur.com/hZLRdhm)

**Comment by Filostorm** [comment]
I'm not sure if you will see this, but I don't really want to open a new ticket. Would it be possible to add similar functionality to Slurry Agitators? It seems as though Unbreakable ones still break, without taking durability loss.

**Comment by GlobbyPotato** [comment]
what do you mean they break without taking durability loss? By default they should work the same way with Unbreaking as the gears. Leaching and Retention Vat gave no issue so far. If you also put Mending they will randomly repair as well.

Will eventually add the same crafttweaker integration, I see you use content tweaker, that would help with high tier agitators.

**Comment by Filostorm** [comment]
They disappear after roughly the same amount of time a normal Agitator takes to break. Used on a server with the Leaching Vat.
The integration you added makes it super clean and easy to visualize the different types of Gears, so I'm looking forward to adding custom Agitators!

That's good to know about mending, I haven't experimented with it yet.

Thanks again!

**Comment by GlobbyPotato** [comment]
This is odd, I made a run with unbreaking 3 and it chew 21 stacks before the first agitator broke. The code is the same as for the sizer. 
For now I made the update to customize the Vats. Will make more tests on that later when I'll have more time.

**Comment by Filostorm** [comment]
Awesome!

I can do some more testing on my end as well, it wasn’t a controlled environment; I didn’t count the amount of materials it processed.

I believe I had set the default durability to 250 as well.

Unbreaking gears I did test, seemed to add on average about 10 extra processes per level. That’s why I opened the ticket in the first place, because it was such a small amount.

**Comment by GlobbyPotato** [comment]
I tried to somewhat replicate the vanilla method to deal with the unbreaking. it's like a dice roll where the 1 does damage, each level adds a face to the dice. if you go beyond level 3  then the higher unbreaking the better (and challenging) is for player to increase levels. once you have mending you may never break a gear

**Comment by Filostorm** [comment]
Ah, I see. I thought it was a flat increase in durability for some reason. The enchanted gears do look extra cool from the outside!

**Comment by Filostorm** [comment]
Okay, I just tested Unbreakable (not Unbreaking) Slurry Agitators, they do indeed break, at exactly the normal amount of processes. Also not sure why, but a 256 durability Crushing Gear crushes 320 items before breaking. That's the normal one configured to 256. 

Thanks for the update allowing for custom Agitators!

Do you have a discord? Might make it a little easier then chatting on here. You are also welcome to join my pack's discord: https://discord.gg/YS2U7Vtxz5

I have a few other suggestions and bugs that I can open new tickets for if you would rather that.

**Comment by GlobbyPotato** [comment]
hmmm will give it a look when possible.

Sadly cannot maintain a discord channel, will jump in the pack room as I have access to my main asset, suggestions are always welcome!
