### ISSUE TITLE
Lab Blender Accepting to much items

### ISSUE THREAD

**Issue by MJRLegends** [GlobbyPotato/Rockhounding_Chemistry#14]
Hello, a player of my mod pack reported this bug today,

See https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/issues/107
They are using 1.54 of your Rockhounding Chemistry but i tested for you on 1.55 and i had to a look through the 1.55 commit so i know that its a still standing bug :P 

Need any more information i can help out. Just let me know 

MJRLegends

**Comment by GlobbyPotato** [comment]
The lab blender is still in progress for future improvements of the logic 
As for now, the recipe of the lab blender is like a shaped crafting recipe: ingrendient1, ingrendient2...ingrendient9. It can't be slot cumulative or will be considered both the same recipe but handled once.
Will try to eventually fix the handling

**Comment by GlobbyPotato** [comment]
Update: actually the check for mismatching ingredients was already there, but for some reason it was not being fired. Made an hotfix for that, If you put coal in two slots it will not operate.

**Comment by MJRLegends** [comment]
Thank you
