### ISSUE TITLE
[Question] why isn't there a CT Script for the evaporation chamber?

### ISSUE THREAD

**Issue by gatoborrachon** [GlobbyPotato/Rockhounding_Chemistry#140]
well, being short: while i was trying Growthcraft i saw that it has Liquid whey, and Heat&Climate has dustWhey, and i thought that it would be nice to evaporate the liquid whey to get the dust from Heat&Climate, at the end Growthcraft has a serious issue with some of its machines and i deleted it so i just ended with the doubt: Why there's not a CT for the evaporation chamber?

**Comment by GlobbyPotato** [comment]
hi, the evaporation tank is a specific system I made for the mod. It has a own process that's why it is not integrated.
Something more generic could be done I guess. It needs to find some application to put it in work inside the mod

**Comment by gatoborrachon** [comment]
well, you are right, there are no reasons to implement another evaporation tank, and maybe less reasons to just do it for crafttweaker, thanks for the answer
