### ISSUE TITLE
[Bug] Mineral Sizer Power

### ISSUE THREAD

**Issue by Filostorm** [GlobbyPotato/Rockhounding_Chemistry#141]
When an Induction Coil is in the Sizer and it gets some RF, it does not consume any power to run.

**Comment by GlobbyPotato** [comment]
hi, the RF storage of the power station has an inner buffer other than the actual tank, so it drains from there making it looking like it's not consuming power. Once drained the power starts going down as usual.

**Comment by Filostorm** [comment]
You’re saying it has a third buffer apart from the two visible ones?

**Comment by GlobbyPotato** [comment]
not a third buffer, it's a small I/O buffer for service purposes when acquiring RF, not worth counting

**Comment by Filostorm** [comment]
I’ll test this out when I get a chance, but it’s not that big of a deal. Thanks!
