### ISSUE TITLE
[Suggestions] Tooltips

### ISSUE THREAD

**Issue by Filostorm** [GlobbyPotato/Rockhounding_Chemistry#143]
Hello again! While making my pack, there was a few things I ended up doing that I think would be helpful for the mod. 

1) Add tooltips for which shards come from Leachate. I added this after picking a shard I wanted to get, only to realize it was only available from leachate. The GUIs in JEI look similar enough at a glance that it can be tricky to tell them apart. 

2) Add a list of which blocks are required in the controller’s tooltip. This is something I started doing because if it’s your first time playing the mod you might not realize that machines are multiblocks. 

3) Add an ore processing system. I’m assuming you’ve probably thought about this, but I’m suggesting it to increase its usefulness before you complete the system to be able to extract from Uninspected Minerals.
I added a complete 8x ore processing system to my pack that follows along with the processing of Uninspected Minerals. Everyone I talked to about your mod always asked me how good of ore processing it had, so I decided to add my own. 

Again, thanks for adding the ability for custom gears and agitators!

**Comment by GlobbyPotato** [comment]
If it's the similarity between leaching and retention vat I changed the jei gui so the two processes will show differently. The R key should point in the right machine. I think extra tooltip may get confusing if crafttweaker remove any of them.

About the blocks there is the guidebook showing this. Players will need to check it anyway to start, so that would be extra computing being added.

Yeah, there is an idea to spread some of the production in lower tiers, in conjunction with some gregtech compatibility. The mod primarily focuses on gating rare elements and customized ones at the end of it, but also on the customization, so you can use the machines in the order you want to manipulate products. Some intermediate farm would be an idea though.

Thanks

**Comment by Filostorm** [comment]
Looking forward to the new JEI display for those!

I actually ended up making 3D fake recipes for each machines using Compact Machines Miniaturization field, I'll post a screenshot of it later. Might just be me, but I really feel like it makes it easier to understand when you can see what it takes to make it.

Would it make more sense to make a new addon mod for Chemistry that handles ore processing?

**Comment by Filostorm** [comment]
![2021-04-24_15 10 28](https://user-images.githubusercontent.com/73716145/115970262-4a070a80-a50f-11eb-8191-b26428b1df82.png)
This was my solution. Not that I'm suggesting this lol.

**Comment by GlobbyPotato** [comment]
That's probably the solution people were looking for long time LOL. 
If the model can be rotated by mouse dragging it helps to spot the plugs by their color.
Will give it a look when possible to see how the integration works. Thanks for letting me know!

**Comment by Filostorm** [comment]
Unfortunately there are a few downsides to this method, first off, you can’t rotate it, it just rotates slowly on its own. Second, for blocks that are 2 tall, it shows both as a separate block. Third, if there is more then a certain amount of blocks in the recipe they overlap each other in the ingredient list. 

Just being able to see them in JEI is worth all that though.

**Comment by GlobbyPotato** [comment]
I see. When I'll have again a decent buff of time at once I'll try to reintroduce the Constructor Tables, like in 1.10, where you put all the requested blocks in a gui and it will assembly the structure itself in front of it.

**Comment by Filostorm** [comment]
That sounds extremely helpful! The most common questions that comes up are in relation to assembling the machines. 

The other way to display them in JEI would be to use Modular Machinery. This fixes the mentioned 3 issues, but has its own downsides. 

First off, you have to have a controller touching the machine to have it be a valid machine for JEI. Second, you can’t see the actual blocks in jei to get crafting recipes, so you won’t know the visuals exist unless you check which Modular machines are added. 

Both those downsides outweigh the other ones, so I decided to keep it in that method.
