### ISSUE TITLE
[Doubt] what is the Flue Gas for?

### ISSUE THREAD

**Issue by gatoborrachon** [GlobbyPotato/Rockhounding_Chemistry#145]
well, this may be akward, but i can't find a use for the Flue gas, the Syngas can be consumed, but i cannot do it with the Flue gas nor can find info about it in the guide (at least not in a quick review), so what is the Flue Gas for?

**Comment by Primitive-Human** [comment]
It's used in the catalyst regenerator alongside water to 'repair' damaged catalysts back to full condition. 
![3f171cd30f32798b0fca5d52188c23af](https://user-images.githubusercontent.com/81650773/113049726-439da100-91a4-11eb-8577-781b4af06321.png)
Other than that there's no use for flue gas as of yet.

Although it may be a nice addition where you use cryogenic distillation to obtain some gases from the flue gas, such as higher amounts of carbon dioxide and use that in further chemical reactions (which also need to be added).

**Comment by gatoborrachon** [comment]
oh, many thanks, i already saw that machine (not in the book) and i can't believe that i don't saw that detail
