### ISSUE TITLE
[Suggestion] Recognition of liquid XP from other mods

### ISSUE THREAD

**Issue by Primitive-Human** [GlobbyPotato/Rockhounding_Chemistry#150]
Right now Rockhounding Chemistry only recognizes liquid XP from Open Blocks and not when a different mod (Ender IO, Thermal Expansion etc) adds it. If I wanted to export liquid experience from the Orbiter I must have Open Blocks installed just for the liquid XP that OB adds, even though I already have liquid XP in Ender IO. 

What I propose is adding support for liquid XP from any mod that adds it (even though I only know Ender IO, Thermal Expansion/Foundation and Industrial Foregoing also adds it.) 

If not,  allow the insertion of empty glass bottles into the orbiter to fill them with experience; ~10 xp per bottle seems appropiate as the minecraft wiki page on the Bottle o' Enchanting says that the bottle gives between 3 and 11 xp with an average of 7 xp. These filled bottles can then be pumped out.

**Comment by gatoborrachon** [comment]
a User-Side solution for this is to use the Transposer to change the XP liquid of other mods to the OpenBlocks one, but if you mean that you don't want to have OpenBlocks, well, then maybe GlobbyPotato can add that small compat feature onto the next release (or at least support one of these XP fluids from other mods)

**Comment by Primitive-Human** [comment]
While the first solution (transposer) is doable,  you still need to have OpenBlocks installed to have fluid XP as an exportable product from the Orbiter, even if other mods register the fluid with the same fluid registry name.

**Comment by GlobbyPotato** [comment]
Hi, sorry for the delay, got some days off.
I didn't know there were multiple fluid xp around (not hard to guess though). I made an update in the Orbiter so to be more customizable, but I kept some peculiar features to preserve the mod spirit.
Added a selector with the extra fluid xp you may want to add with crafttweaker, but you will see only the owner mod, supposing you add only fluid xp for this purpose. So you can choose between "OpenBlock", "EnderIO", "ThermalExpansion" etc.... It will show though what fluid xp the mod is adding as well. If fluids have the same registry name through mod you will sww only the one created of course
Also added a config section where you can set the chance to double the XP value of the orb by (yet another) infusion of the Toxic Waste and the quantity of waste consumed if chance happens.
The script will be like:
`mods.rockhounding_chemistry.Orbiter.add(<liquid:water_vapour>*1000);`

If you select in example a different mod while the orbiter tank contains OpenBlock fluid in it, orbs will remain unpicked, so you may want to drain the tank first. By barring the drain you can retrieve the levels as usual with the button on top.

**Comment by Primitive-Human** [comment]
Thanks for this update, this will do nicely.

**Comment by Primitive-Human** [comment]
Reopening this issue, because now the Orbiter won't function (pull in XP orbs) unless you have a mod that adds liquid XP, as you're stuck on the "No Liquid XP selected" 'recipe'. 
RH Core: 1.12.2-3.26
RH Chemistry: 1.12.2-3.57

**Comment by GlobbyPotato** [comment]
I extended the working to the No Liquid mode. Now setting No recipe will fill the XP bar to retrieve levels, while setting any fluid will the tank. Also with a fluid installed, selecting it, it will pull the stored XP of the bar into fluid automatically, stopping if you return to No Recipe or turn the orbiter OFF. Priority is given to liquid xp, so if you need only levels you need to select explicitely the No recipe mode. I'm trying to avoid too many gui interactions and switches for a basically straight forward feature orb-to-liquidXp.
