### ISSUE TITLE
[Suggestion] get different types of Air (dynamically generated) depending on the actual dimension

### ISSUE THREAD

**Issue by gatoborrachon** [GlobbyPotato/Rockhounding_Chemistry#151]
Description:
Note: This suggestion is focused on Modpack Makers.

1.- Make the Cryogenic Distillation Plant to dynamically generate different Airs depending on the dimension (at the start, each air can be named according to its Dimension ID, like "57 Air" or "-1 Air").
2.- Then there can be a Config File (with all the new Airs dynamically generated with the defaul values of Earth Air) where you can find things like the name of each Air (to be able to change it) and the different output gases with its quantities (6 maximum).

Uses:
This can be handy to get a rare gas on another planet with mods like Advanced Rocketry or Galacticraft.

Additional notes: 
well, i know that even consider this requires a lot of work on the logic part of that Multiblock, and since you have so little time i just want to write this down (before i forget it) to see what do you think.

**Comment by GlobbyPotato** [comment]
I like this plan but the problem is that the Cryogenic plant is too hardcoded to be so open to customization and I don't really like the idea of playing with dimension IDs. Acquiring "lunar air" makes me shiver though. The easiest way is to open the customization to full recipes by creating new input material to process. I was thinking to make a small twist in the plant to work as an "Atmosphere Sampler". Instead of Compressed Air you can create a custom fluid representing the dimension atmosphere and process it to obtain your 2main + 6rare  gases. The sampler can have its own features, like requiring to be placed next to the top height, mark the recipe as corrosive or non-corrosive and so on...

**Comment by gatoborrachon** [comment]
> I like this plan but the problem is that the Cryogenic plant is too hardcoded to be so open to customization and I don't really like the idea of playing with dimension IDs. 
> The easiest way is to open the customization to full recipes by creating new input material to process. I was thinking to make a small twist in the plant to work as an "Atmosphere Sampler".

well, that would be a better fix.


.
> Acquiring "lunar air" makes me shiver though. 

yeah, i forgot to specify planets like Venus or Saturn's moons like Titan.


.
> Instead of Compressed Air you can create a custom fluid representing the dimension atmosphere and process it to obtain your 2main + 6rare gases. 

i already made a custom mod to add some specific recipes in mods that doesn't have Crafttweaker support and i made some custom fluids, so this wouldn't be a problem and instead a better solution.


.
> The sampler can have its own features, like requiring to be placed next to the top height, mark the recipe as corrosive or non-corrosive and so on...

interesting, lets see what big Modpackers like Wormzjl think about this (should i ping him? i don't think that this would be made in a short-time)

**Comment by GlobbyPotato** [comment]
> yeah, i forgot to specify planets like Venus or Saturn's moons like Titan.
indeed, that would open to all scenarios without getting limited by the air process itself.

>i already made a custom mod to add some specific recipes in mods that doesn't have Crafttweaker support and i made some custom fluids, so this wouldn't be a problem and instead a better solution.
that's the best way to save space if you need specific items. I can add a process for reference, then anything else is doable.

> interesting, lets see what big Modpackers like Wormzjl think about this (should i ping him? i don't think that this would be made in a short-time)
I don't know, not necessary I guess. I seem to read time ago that he migrated to other versions/mods

**Comment by gatoborrachon** [comment]
> I don't know, not necessary I guess. I seem to read time ago that he migrated to other versions/mods

i can still see the Rockhounding config file inside the config files of his newest modpack 
https://github.com/wormzjl/Fabrica-Atlantica/blob/master/config/rockhounding_chemistry.cfg

**Comment by gatoborrachon** [comment]
Well, after looking at my open issues and thinking a bit about this one, the main (and biggest) sources of gasses in other planets would be from the Gas Giants (like Saturn or Jupiter), planets where you can't land to extract these gasses 

(Also, Advanced Rocketry already implements a way to extract gasses from these type of planets (Gas Giant gas/fluid mining)), so the only case where the asked feature in this issue would be helpful is in planets with atmospheres (and usually with living entities, like an [exotic planet](https://astroneer.fandom.com/wiki/Vesania) from [Astroneer](https://astroneer.fandom.com/wiki/Atmospheric_Condenser), another game).

But since it is almost an edge case (And well, if i were to an exotic planet like the Twilight Forest i would go mostly for the adventure and the ores, not for the gases), i think this would not worth the effort to rewrite the logic of the Cryogenic Distillation Plant, so i will close this issue.

(Unless you actually wanted to implement this feature, feel free to re-open it)
