### ISSUE TITLE
[Bug] Chemical Extractor Server

### ISSUE THREAD

**Issue by Primitive-Human** [GlobbyPotato/Rockhounding_Chemistry#155]
I may have misunderstood how the server functions with the Chemical Extractor (I have made sure that the multiblock setup is correct, as I have it memorized from testing it multiple times). But most of the time I built it without the server attached. The times I do try to use the server,  it does not seem to function at all with the chemical extractor.
![2021-05-18_02 08 34](https://user-images.githubusercontent.com/81650773/118571338-1ae66080-b77e-11eb-8184-caf03f46e1e4.png)
I placed the server behind the glassware holder, pointing at it. Next I put a shard (Monazite) in the Server filter slot, programmed a server file to perform 1 craft at Intensity 1 (non-repeatable) and put it in the row of program file slots. I turned the server and the chemical extractor on in that order (button, not redstone), set the default intensity at 8 and then put a monazite shard into the chemical extractor input slot.
![2021-05-18_02 08 49](https://user-images.githubusercontent.com/81650773/118571374-2b96d680-b77e-11eb-841b-c8991424d88f.png)
![2021-05-18_02 08 58](https://user-images.githubusercontent.com/81650773/118571381-305b8a80-b77e-11eb-80f2-ad180344358b.png)
![2021-05-18_02 09 10](https://user-images.githubusercontent.com/81650773/118571387-32bde480-b77e-11eb-928a-a60c2135beff.png)
![2021-05-18_02 09 16](https://user-images.githubusercontent.com/81650773/118571415-42d5c400-b77e-11eb-9600-c9f8a955e643.png)
      I've not missed any items where they belong (Ferrous catalysts in the Stabilizer, Graduated cylinder and Test tube in the Glassware Holder (not in the tops of the cabinets as they're not necessary for the reaction,  only to obtain the dusts from the cabinets),  power and heat in the Power station (syngas + gas turbine) and sodium cyanide and nitric acid in the Fluid Input system in the correct tanks. This is where the server seems to be broken:

I had hoped that the chemical extractor would change its intensity to the intensity in the server file (intensity 1). This does not happen at all as the intensity remains at the default (intensity 8).

**Comment by GlobbyPotato** [comment]
Hi, I think I spotted the problem, it was reading the wrong variable so the intensity was not overridden by the server. Thanks for reporting it and sorry for the issue. Will fix it as soon as I can edit it.

**Comment by Primitive-Human** [comment]
Okay, the server automation is working as it should now. Although a tiny new issue popped up (probably unintended): 

You can set the intensity at 0 in the server,  which means the chemical extractor is able to just spend 1 mB of nitric and and 1 mB of sodium cyanide per process, much lower than the 10/20 mB at intensity 1.

**Comment by GlobbyPotato** [comment]
oh, I think I know what it is. For intensity, zero is not an option differently than usual recipes for other machines, hence server value needs to be set +1. Thanks for spotting it.
