### ISSUE TITLE
Fixed Bed Reactor refuses to make propyline

### ISSUE THREAD

**Issue by Cormenthor** [GlobbyPotato/Rockhounding_Chemistry#156]
I've spent several hours again today checking and rechecking this thing and it just won't craft propylene to save my back side.
This is in the mod pack Dungeons Dragons and Space Shuttles version 8.0-R1 (the final finished release version).

Rockhounding Mod Core   1.12.2- 3.22
Rockhounding Mod Chemistry 1.12.2- 3.52

Screen shots of the build and machine interfaces included.
Any help would be greatly appreciated, thanks in advance.
![2021-05-25_19 10 52](https://user-images.githubusercontent.com/50423213/119594536-d61b8480-bd90-11eb-87ce-046e4e010787.png)
![2021-05-25_19 10 59](https://user-images.githubusercontent.com/50423213/119594541-d9167500-bd90-11eb-8b02-a5bbcdd96096.png)
![2021-05-25_19 11 07](https://user-images.githubusercontent.com/50423213/119594551-dca9fc00-bd90-11eb-8247-4cc68354329a.png)
![2021-05-25_19 11 27](https://user-images.githubusercontent.com/50423213/119594570-e3387380-bd90-11eb-8800-7d7a81d7b51e.png)
![2021-05-25_19 11 31](https://user-images.githubusercontent.com/50423213/119594600-f2b7bc80-bd90-11eb-846c-9db712688db5.png)
![2021-05-25_19 11 45](https://user-images.githubusercontent.com/50423213/119594626-fe0ae800-bd90-11eb-948e-e01a8816e78a.png)
![2021-05-25_19 11 49](https://user-images.githubusercontent.com/50423213/119594632-ff3c1500-bd90-11eb-90bd-291abbdaad4b.png)
![2021-05-25_19 11 57](https://user-images.githubusercontent.com/50423213/119594643-0531f600-bd91-11eb-8bdf-10c230ffefdb.png)
![2021-05-25_19 12 03](https://user-images.githubusercontent.com/50423213/119594646-06fbb980-bd91-11eb-9d94-1dbad0e44b5f.png)
![2021-05-25_19 12 08](https://user-images.githubusercontent.com/50423213/119594651-095e1380-bd91-11eb-8027-c4c53cc357ab.png)
![2021-05-25_19 12 16](https://user-images.githubusercontent.com/50423213/119594654-0a8f4080-bd91-11eb-808f-9a5beba9d190.png)
![2021-05-25_19 12 20](https://user-images.githubusercontent.com/50423213/119594657-0cf19a80-bd91-11eb-9dbd-37057ad33d40.png)

**Comment by GlobbyPotato** [comment]
hi, it could be a problem with vessel capacity. Try to replace the Pressure Vessels with Gas Holders and see if it solves. For mass production they are always more indicated.

**Comment by Cormenthor** [comment]
The one thing I didn't think to try. And now it works perfectly, thank you so much, this is a thing I will keep in the back of my mind, and in my notes when it comes to Rockhounding.
