### ISSUE TITLE
[BUG] Particulate Collector shiftclick gives duped output

### ISSUE THREAD

**Issue by Primitive-Human** [GlobbyPotato/Rockhounding_Chemistry#157]
The particulate collector (both on the Gasifier and Gas Purifier) gives double the output item when shiftclicking it into your inventory. It does not seem to happen when dragging the items however. 

MC: 1.12.2
Forge: 14.23.5.2854
Bookshelf: 2.3.590
Guidebook: 2.9.4
Redstone Flux API: 2.1.1.1
Rockhounding Core: 3.26
Rockhounding Chemistry: 3.57

**Comment by GlobbyPotato** [comment]
thanks, noted. It should be fixed now.

**Comment by Primitive-Human** [comment]
Seems to be fixed now. Closing.
