### ISSUE TITLE
[Suggestion] Dependencies

### ISSUE THREAD

**Issue by Primitive-Human** [GlobbyPotato/Rockhounding_Chemistry#160]
You may have heard this suggestion before,  but an issue search didn't really give some results on this.  Anyway.
Have you considered ditching the Redstone Flux API and instead adapt the Forge Energy API? The latter is what the majority of mods use rather than depending on the RF API. 
This mod is also the only reason why I still need to have the RF API installed whereas most/all other mods don't.

**Comment by GlobbyPotato** [comment]
This dependency is inherited from older MC versions and remained untouched because there is a risk to mess too much with the code. It also uses the FE when it was added, but at this point it's not worth the chance, couldn't even open the game in a while.
