### ISSUE TITLE
[Bug] Catalyst Regenerator seems does not work on Fixed Bed Reactor

### ISSUE THREAD

**Issue by StarryNeverFall** [GlobbyPotato/Rockhounding_Chemistry#165]
First of all, Catalyst Regenerator can work smoothly on other structures.I put the catalyst regenerator under the _fixed bed reactor controller_ in the same way.However, the catalyst in the _fixed bed reactor chamber_ has not been repaired until it is damaged.
In other structures, the catalyst is placed in a machine close to catalyst regenerator.Only the catalyst of the fixed bed reactor needs to be placed in the _fixed bed reactor chamber_.Is this the cause of the error?

**Comment by GlobbyPotato** [comment]
Thanks, fixed it. It seems working now.
In this machine the catalyst regen had to be placed in a different spot to fit the contraption regen+vessel, otherwise a block of the structure would remain hidden on all sides.
