### ISSUE TITLE
Speed upgrade decreases particulate production

### ISSUE THREAD

**Issue by Primitive-Human** [GlobbyPotato/Rockhounding_Chemistry#166]
According to my tests,  a speed upgrade in a machine with a particulate collector reduces particulate production. I compared a gas purifier setup with filled raw syngas gas holders without a speed upgrade, one with a tier 1 upgrade (2x speed) and another with a tier 7 upgrade (8x speed). 

After all 1,000,000 cu of raw syngas has been purified,  the purifiers (no upgrade, tier 1 and tier 7 upgrades)  produced ~270, 138 and 35 fly ash compounds respectively. This seems to be inversely proportional to the speed multiplier of each upgrade.

It seems that multiplying the input and output amounts of each craft process treats it as a single crafting process, which overall reduces the chances at getting particulates too. 

So, is this a bug, or intended? If it's a bug, would you multiply the particulate production according to the speed upgrade being used, or reduce the time it takes per craft instead of multiplying the input/output amounts? 

If it's intended,  I'll settle with multiple purifiers without speed upgrades, if I want to focus on particulate collection.

RHC: v1.12.2-3.60

**Comment by GlobbyPotato** [comment]
Thanks for reporting it. I was thinking how to manage it but remained untouched since then. I adjusted it so it follows the speed factor as well.
