### ISSUE TITLE
[Suggestion] Let the Toxic Sludge FluidBlocks to be able to spawn in any replaceable block

### ISSUE THREAD

**Issue by gatoborrachon** [GlobbyPotato/Rockhounding_Chemistry#167]
**What is happening**
you can by-pass the negative effect of pollutants in Fluid Tanks that are surrounded by soft blocks like Grass or Snow (and i guess that any block that isn't air, as [this line](https://github.com/GlobbyPotato/Rockhounding_Chemistry/blob/02ccc1987ed2a0f7ed0dec16e63601107b248f1f/scr/main/java/com/globbypotato/rockhounding_chemistry/machines/tile/IToxic.java#L34) suggest)

**Screenshots**
+Fluid Tanks filled with Nitric Acid that are not spawning Toxic Sludge.
![2021-09-18_17 33 29](https://user-images.githubusercontent.com/61126174/133910668-6d1c15ce-c6d7-4904-914f-f37768843dc0.png)

+Fluid tanks in a clean area spawning Toxic Sludge
![2021-09-18_17 33 37](https://user-images.githubusercontent.com/61126174/133910664-44f8d086-aadb-409d-a639-fcda170494a6.png)

**Suggestion**
1.- Be able to spawn these FluidBlocks of ToxicSludge in every soft block (like the previously described)
2.- Or, if you consider it better, maybe it could be added a config option where the user can add the blocks that can be replaced by the Toxic Sludge, with the Grass and the Snow as default (in case you choose this one, consider blocks with metadata)

**Additional Notes**
 i noticed about this while i was testing the IToxic Interface in the FluidTanks of another mod

**Comment by GlobbyPotato** [comment]
Hi, previously the pollutant spawning was less forgiving, I turned into this to make sure it did not create awkward situations, expecially with redstone lying around, to avoid floating spawning or in case of particular replaceable modded blocks. 
Tinkering the factory with carpets or soft blocks was already considered as a trick. Will see eventually if to set a config to chose between a hard or safer way.

**Comment by gatoborrachon** [comment]
oh, ok, i think the last option (adding a config to choose between hard/easy hazard features) would be the best, thanks for answer, and yeah, it would be nice to affect modded replaceable blocks too

**Comment by GlobbyPotato** [comment]
I made a quick fix on the fly to see how it works. I made sure any isReplaceable() occurrency I found is checked.
Also added a config to change the radius of the polluting area.

**Comment by gatoborrachon** [comment]
ok, let me test it in some hours and i will close the issue, many thanks

**Comment by gatoborrachon** [comment]
Works pretty fine, many thanks
![2021-09-20_21 42 03](https://user-images.githubusercontent.com/61126174/134104101-0b9f7fe7-5305-4224-9ce5-fc1be328479b.png)
