### ISSUE TITLE
Salt Seasoner outputting zero stacks; other weirdness

### ISSUE THREAD

**Issue by belathus** [GlobbyPotato/Rockhounding_Chemistry#17]
I've had an automated evaporation tank next to a salt seasoner for a while now, but it is outputting far less salt than I'd expect, which made me watch it after I saw it put a bunch of salt into the seasoner. the hopper grabbed a zero stack of salt from the seasoner when it finished. So, I removed the hopper and watched it and got the below screenshot:

https://imgur.com/a/ops6v

I have 3 seasoners near each other, all automated (because I need a lot of salt, and removed the Pam's Harvestcraft recipe for salt). I removed all the hoppers and saw 7 salt finish being seasoned and in the output slot. Went to one seasoner, grabbed the salt, then went to the next and saw both had zero stack (after verifying that all of them had 7 salt in the output slot just moments before).

Now, I'm not running the absolute latest version of Rockhounding Chemistry (1.10.2 - 1.51), but I don't see any changes to your code related to the salt seasoner in the past few months. I plan on updating my server tomorrow; I can check again at that time if you'd like.

**Comment by belathus** [comment]
As a followup, it seems to work fine if I make sure I don't pull out all of the salt from the output slot. I've swapped the hoppers with EnderIO conduit with a counting item filter.

**Comment by GlobbyPotato** [comment]
Hi, thanks for reporting. You are right, the block stopped handling the output slot while empty, pretty sure it worked previously because I've been using it too. I'm uploading an hotfix 1.60 that should fix it. 
Sorry for the issue.

**Comment by belathus** [comment]
All good. I just wanted to point out this one, too: https://imgur.com/a/FerTY

**Comment by GlobbyPotato** [comment]
This one does not happen to me. 
when does it happen? Try to break and place again the block eventually to refresh the tileentity

**Comment by belathus** [comment]
It does it as the seasoning rack is running. As I'm watching it, I see the amount of salt in the input slot slowly decrease to negative numbers faster than the operation time of the seasoning rack. I'm gonna see if updating the mod resolves that one, at least.

**Comment by GlobbyPotato** [comment]
It looks like something has gone static, so you are seeing the seasoning racks decreasing all the others too.
I reverted something so it should no longer happen.

**Comment by belathus** [comment]
I was about to suggest that it might have something to do with having multiple seasoning racks. I wasn't seeing that issue when I only had one.
