### ISSUE TITLE
Crash 1.10.2-1.61 with TileEntityMineralSizer

### ISSUE THREAD

**Issue by MJRLegends** [GlobbyPotato/Rockhounding_Chemistry#19]
When updating from rockhounding_chemistry-1.10.2-1.60 to rockhounding_chemistry-1.10.2-1.61 i get the following crash: https://pastebin.com/XbrcKhJE

**Comment by GlobbyPotato** [comment]
Hi, you just need to break the block and place it again to refresh the tile entity before you open the gui, I warned in the changelog about this.
It's an annoying thing but people imprecated at me for the machines being slow though the speed always been configurable, so I had to add a speed upgrade slot to stop that.
It happens for 6 main machines. Just break and place, fluids will be stored.
It's the only change in 1.61, so you can avoid this update. Really sorry about that.

**Comment by MJRLegends** [comment]
I cant break it as it just crashes out the world and even tho i know how to remove blocks, the other 1000+ players of my mod pack probably dont

**Comment by GlobbyPotato** [comment]
Breaking it has not caused crashes here, if it crashes on ticking, probably there was a machine activated during the update and not recognizing the slot. They should be just turned off before the update and broken right after to refresh. I haven't found yet the exact place where to inject this refreshing fix.

**Comment by MJRLegends** [comment]
I understand what you mean, but getting all players to turn off there machines before updating to a different mod pack version. That will just a massive headache for me to deal with, any chance you can just add a checker before getting the slot and force stop the machine.

As i dont think i can use the latest update if its going to require players to turn off machines before updating as about 40% of players will ignore all my messages on it

**Comment by GlobbyPotato** [comment]
Well, after all people not reading messages cause bad updates like this :P
I will test further and see if I can force the stop after the update.

The 1.10.2 mod is basically over so the latest update is not really necessary anycase

**Comment by MJRLegends** [comment]
Yeah i understand, like personally i can do the disabling of them before updating but im not sure i wanna have to deal with lots of issue reports on this, im sure yoy being a mod dev understand how annoying that could be.

I'd appreciate it.

You should just be able to add checks if the slot exists

**Comment by MJRLegends** [comment]
Also server network owner's cant always get 100% turned off machines at once so they would be having to remove blocks multiple times as they are found/players login after a while

**Comment by MJRLegends** [comment]
Or another way could be just to change the machines unlocalized name so it gets rid of the machine altogether and they have to remake them

**Comment by MJRLegends** [comment]
You should just be able to add a check here https://github.com/GlobbyPotato/Rockhounding_Chemistry/blob/master/scr/main/java/com/globbypotato/rockhounding_chemistry/machines/tileentity/TileEntityMineralSizer.java#L101 for if the slot exists and if not just return a default value this will stop it checking for the slot in the tile entities if it doesnt exist

**Comment by GlobbyPotato** [comment]
I think the problem is deeper, at the level of the Forge code. It stores the number of slots, so on reload the newly added falls out of bound. At that breakpoint it already failed. 
I can fix it by updating the inventory size and it does not even require the breaking part even when active, but it causes the inventory to clean.

**Comment by MJRLegends** [comment]
yeah that sounds good

**Comment by GlobbyPotato** [comment]
ok I think I found a working compromise. Got to clean the core and update all the modules as well.
It doesn't clean the inventory anymore, so should work straight away after the update, will put it up soon. Got no crashes on testing on both Sides, hopefully should be stable.

**Comment by MJRLegends** [comment]
Nice i appreciate it
