### ISSUE TITLE
[1.10.2-1.58] [CRASH] - Two output pipes on an activated pump causes immediate crash.

### ISSUE THREAD

**Issue by JaSpr** [GlobbyPotato/Rockhounding_Chemistry#20]
I was setting up the Rockhounding Cryogenic Distillation Plant for the first time, and realized it would be too much work to manually try to fill it with water (for coolant), then I realized that there was a pump, so I set it up, ran a pipe out of one side, then ran a pipe out of another side... Then, as soon as I turned it on the server crashed.  Now the server continues to crash whenever I log in.

It seems that the issue is with having two pipes connected to an activated pump.

[Crash Report](https://gist.github.com/anonymous/6dbd6ec4636f53002e9048a127f6cb8d)

This also reproduces in a local game, in which case the client crashes as well.

Steps to reproduce:

1) Place pipeline pump
2) place pipeline on on side,
3) place another pipeline on another side (I did it at a right angle)
4) activate pump

**Comment by GlobbyPotato** [comment]
Hi, thanks for reporting and sorry for the inconvenience. You are right, for some reason a line of code was no longer there, breaking the math. Will fix it asap.
BTW you can hook the produced nitrogen itself for coolant, It will save you water automation and RF.

**Comment by JaSpr** [comment]
Thanks!
