### ISSUE TITLE
Element cabinet will not output to scale unless fed another dust

### ISSUE THREAD

**Issue by kiwifrogg** [GlobbyPotato/Rockhounding_Chemistry#22]
Mod Version rockhounding_chemistry-1.12.2-3.03
Forge 14.23.2.2611

I've built the chemical extractor, it works, and fills the element cabinet with (in this case) osmium. It says 4 or 5 dust available but it does not appear on the scale if I place another dust (like iron for example) in the top of the cabinet with a cylinder then the 1 osmium will pop out, but then if I put more iron in then only iron comes out(I have a hopper under).   I have a test tube and cylinder in the glass holder, nothing in the white cabinet, tried with and without cylinder in the element cabinet.   

Have I missed something, or is this a bug?

**Comment by GlobbyPotato** [comment]
Thanks for reporting, I think I accidentally bugged the cabinets, not updating properly. Will make asap an hotfix to solve it

**Comment by kiwifrogg** [comment]
Wow, Thanks for the fast fix, looking forward to getting home to try it :)

**Comment by kiwifrogg** [comment]
Works perfectly now :)
