### ISSUE TITLE
Visual Error when rendering Gas Pipeline Pump

### ISSUE THREAD

**Issue by cScotPlay** [GlobbyPotato/Rockhounding_Chemistry#23]
When connecting the gas line to either the pressure vessel or the gas holder the valve doesn't appear to connect.  It still pulls fluid from both systems and works just fine.  This is connected to the orange side of the blocks.
![2018-03-06_23 28 50](https://user-images.githubusercontent.com/33098040/37079065-245c3c10-2196-11e8-9baa-e9f70d3ae01b.png)

Versions:  
1.12.2-3.04 Chemistry
1.12.2-3.06 Core API 
No other mods installed other than One Probe and JEI

By the way love the mod and all the modeling of the models and textures.

**Comment by GlobbyPotato** [comment]
Hi, thanks for reporting, Found it, yes it's just a visual glitch, the pump itself still works. Will fix it on next update.
Glad you like the mod.
