### ISSUE TITLE
[1.12.2][Bug] Crafttweaker Recipe add to Prifiling Bench automatically use oredict when use specific

### ISSUE THREAD

**Issue by Fireztonez** [GlobbyPotato/Rockhounding_Chemistry#24]
I create a recipe for the Profiling Bench, using a specific type of wood log for make the Wooden gear from Better With Mod, but when I try, the recipe show in JEI with all log, like if I make a Oredict recipe... I try with different log wood and it work with any... That is a realy strange bug!!

Screenshot of recipe in JEI:
![2018-03-08 15_32_36-minecraft 1 12 2](https://user-images.githubusercontent.com/19277301/37174945-02e89140-22e6-11e8-8e80-738244722aa2.png)

Crafttweaker script for your mod:
https://gist.github.com/Fireztonez/f355554426c862ce89c44ecd7904e8d5

Minecraft: 1.12.2
Forge: 14.23.2.2616
Rockckhounding Core: 3.0.6
Rockhounding Chemistry: 3.0.4
Crafttweaker: 4.1.5

**Comment by GlobbyPotato** [comment]
Hi, thanks for reporting.
There was a bit of lack in setting up the recipe structure, will fix it on the next update shortly. You'll be able to use either a script with a specific itemstack with no oredicted variants, or a script with an oredict string that will extend to all variants (like the log in the issue). Will update the script examples here on github as well when ready.
Sorry about that.

**Comment by Fireztonez** [comment]
No problem, thanks for the answer.
I am a modpack developer and a web developer, so I can fully understand what programming is and what bugs can happen, often due to a simple verification that was not done or a simple oversight. So, when I see a bug, I always try to report and do everything I can to give as much information as possible about the problem, to help the developer solve the problem.

Fireztonez
