### ISSUE TITLE
1.12.2 Lab blender

### ISSUE THREAD

**Issue by Dominance** [GlobbyPotato/Rockhounding_Chemistry#26]
Unless I am missing something, how in the world does this thing work. 

Setup
https://i.imgur.com/rduJP2n.png
Top part
https://i.imgur.com/W2lk1Sp.png
Bottom part w redstone 
https://i.imgur.com/A9JhfFv.png
Bottom part w/o redstone
https://i.imgur.com/l1nL0Vb.png

I have tried it with every recipe and nothing is making it produce anything at all. The wiki on curseforge is of course out of date. the guidebook in game doesn't display information on how to make it work.

https://i.imgur.com/1EXmqlB.png Current version i am using 

On a side note. the current guidebook is nice and all but I would suggest looking at https://minecraft.curseforge.com/projects/rtfm?gameCategorySlug=mc-mods&projectID=268344 This way you can have the resources available with ease on a github wiki or anything that supports markdown format and in game. You can even package the mod (change name) similar to how better with mods has done it https://i.imgur.com/hKjbPMd.png inside your mod so you do not have to rely on a separate mod to be installed.  https://github.com/BetterWithMods/BetterWithMods/tree/1.12/src/main/java/betterwithmods/manual

**Comment by GlobbyPotato** [comment]
in the setup image, the power station must be placed flipped by 180 degrees. The tighter part must always point to the machine you connect.

Thanks for the suggestion, I'll give it a look. This was the first workable system I found to make the ingame guide.

**Comment by Dominance** [comment]
Holy heck it worked. I spent a good few hours and for some reason i missed this layout i guess. Thanks agian
