### ISSUE TITLE
Recipes missing?

### ISSUE THREAD

**Issue by lobbienjonsji** [GlobbyPotato/Rockhounding_Chemistry#27]
A lot of the parts used in the mod are not showing up in JEI, even the first machines that are required, have parts (iron casing, iron coil) with no recipes showing.

**Comment by lobbienjonsji** [comment]
ok I found out, that its simply the jei recipes not working

**Comment by GlobbyPotato** [comment]
Hi, that's strange, I can see all the recipes with no problem. The parts used in most of the recipes are made in the Profiling Bench out of iron ingots and blocks. Are they available and oredicted in your pack?

**Comment by lobbienjonsji** [comment]
They are available. Maybe they were removed by a different mod. I will try it without any other mods and see if it works.

**Comment by lobbienjonsji** [comment]
I see: The recipes are only not working the first time the mod is launched. Strange.
