### ISSUE TITLE
CraftTweaker script not working

### ISSUE THREAD

**Issue by tekcay** [GlobbyPotato/Rockhounding_Chemistry#32]
I want to add recipes to the lab oven, so I copied one section from _CraftTweaker_chemistry_script_1_12_2.zs_. 
```

//Note: one between solute and catalyst must be always used. the solvent and the solution cannot be null.
//display name: alternative name for the recipe selector. Can be null id not needed
//solute stack: the main ingredient (optional)
//catalyst: the damageable ingredient (optional)
//solvent fluid: the main solvent
//reagent fluid: the secondary solvent (optional)
//solution fluid: the output fluid
//byproduct: the secondary output (optional)
//precipitate: the solid output (optional)
mods.rockhounding_chemistry.LabOven.add("Silicone Plus", <minecraft:slime_ball>, null, <liquid:water>*500, null, <liquid:sulfuric_acid>*500, <liquid:silicone>*100, null);

//solute stack: the solute to remove
mods.rockhounding_chemistry.LabOven.removeByInput(<minecraft:slime_ball>);
//solution fluid: the solution to remove
mods.rockhounding_chemistry.LabOven.removeByOutput(<liquid:sulfuric_acid>);
```
Neither JEI or the lab oven GUI shows the new recipe.

Minecraft 1.12.2
Forge 1.12.2-14.23.3.2655
rockhounding_chemistry-1.12.2-3.09
CraftTweaker2-1.12-4.1.8

**Comment by tekcay** [comment]
That's exactly what I did  yeah, I created a .zs file with those lines.
I don't have any errors, neither in the chat nor in the log
[crafttweaker.log](https://github.com/GlobbyPotato/Rockhounding_Chemistry/files/1978064/crafttweaker.log)

**Comment by GlobbyPotato** [comment]
You basically added the recipe and immediatelly removed it again.
Copy only the first line:
mods.rockhounding_chemistry.LabOven.add("Silicone Plus", <minecraft:slime_ball>, null, <liquid:water>*500, null, <liquid:sulfuric_acid>*500, <liquid:silicone>*100, null);

the other two lines are to remove existing recipes in the oven.

**Comment by tekcay** [comment]
Oh ok my bad, so now your example works thank you.
I tried this script but I get an error message in the chat, here is the log too
```
//Note: one between solute and catalyst must be always used. the solvent and the solution cannot be null.
//display name: alternative name for the recipe selector. Can be null id not needed
//solute stack: the main ingredient (optional)
//catalyst: the damageable ingredient (optional)
//solvent fluid: the main solvent
//reagent fluid: the secondary solvent (optional)
//solution fluid: the output fluid
//byproduct: the secondary output (optional)
//precipitate: the solid output (optional)
mods.rockhounding_chemistry.LabOven.add("OrePurif", <mekanism:dirtydust>, <rockhounding_chemistry:pt_catalyst>,<rockhounding_chemistry:fluid.chloromethane>*50, <rockhounding_chemistry:fluid.liquid_ammonia>*50, <liquid:water>*50, <rockhounding_chemistry:fluid.toxic_waste>*50, <ic2:crushed>*2);
```
What do I do wrong this time ?
[crafttweaker.log](https://github.com/GlobbyPotato/Rockhounding_Chemistry/files/1978146/crafttweaker.log)

**Comment by GlobbyPotato** [comment]
I think could be the fluids to be erroring, They don't come with the modid but are taken from the fluid registry by the name
try 
**<liquid:chloromethane>*50 
<liquid:liquid_ammonia>*50
<liquid:toxic_waste>*50**

I dont kow what is <ic2:crushed> but I suppose it is correct

**Comment by tekcay** [comment]
I tried this and replaced ic2:crushed with wheat to just make sure the issue does not come from that. 

```
//Note: one between solute and catalyst must be always used. the solvent and the solution cannot be null.
//display name: alternative name for the recipe selector. Can be null id not needed
//solute stack: the main ingredient (optional)
//catalyst: the damageable ingredient (optional)
//solvent fluid: the main solvent
//reagent fluid: the secondary solvent (optional)
//solution fluid: the output fluid
//byproduct: the secondary output (optional)
//precipitate: the solid output (optional)
mods.rockhounding_chemistry.LabOven.add("OrePurif", <mekanism:dirtydust>, <rockhounding_chemistry:pt_catalyst>,<liquid:chloromethane>*50, <liquid:liquid_ammonia>*50, <liquid:water>*50, <liquid:toxic_waste>*50, <minecraft:wheat>);
```

Still does not work with similar error : 
[crafttweaker.log](https://github.com/GlobbyPotato/Rockhounding_Chemistry/files/1979553/crafttweaker.log)

**Comment by GlobbyPotato** [comment]
That recipe adds correctly here. Dirty Iron dust with liquids and wheat.
Are you sure the error doesn't come from another recipe of your file? What's in row 10 of your file? By the log it seems you probably have the previous recipe still active because you were trying to add the fluid blocks and not the fluids themselves. Try commenting out those row by adding a // at the beginning.

**Comment by tekcay** [comment]
You were right I had a folder in scripts directory containing another script file, so many stupid mistakes. Now it works perfectly with wheat or anything standard. I can't make it work with the crushed ore from IC2 but I don't think it comes from your mod. Thank you for your help and your patience, I appreciated it a lot :)
