### ISSUE TITLE
Evaporation tank fills with water in biomes where it doesn't rain

### ISSUE THREAD

**Issue by belathus** [GlobbyPotato/Rockhounding_Chemistry#37]
I've been living in a savanna biome. I was amused when my evaporation tanks suddenly filled with water while it was raining, even though it doesn't actually rain in savanna biomes.

**Comment by GlobbyPotato** [comment]
The rain filling was denied explicitely in sandy biome to don't hit players with rainfall values for each biome they live in. Anyway, will add the condition for snow and low rainfall biome.
