### ISSUE TITLE
Fluidpedia does not work well with localizations

### ISSUE THREAD

**Issue by wormzjl** [GlobbyPotato/Rockhounding_Chemistry#38]
So I think basically it uses the localized name of each fluid to sort stuff.
However, if the fluid name is localized to other languages, this will no longer work since it can be something else other than A-Z.
I'd suggest to sort it with the actual fluid name or en_us name to prevent such problems.

**Comment by GlobbyPotato** [comment]
yeah, I had already found out that I mispelled the code, too late for the release of course. The plan was indeed to stick to the fluid name.

**Comment by wormzjl** [comment]
ok cool!
