### ISSUE TITLE
Salt n Seasoning Rack

### ISSUE THREAD

**Issue by Chromogen** [GlobbyPotato/Rockhounding_Chemistry#4]
for some reason the seasoning rack wont accept my salt
also there is a missing JEI for raw salt

**Comment by GlobbyPotato** [comment]
Fixed the slot accepting raw salt, it should have been already working actually, made it cleaner,
There wasn't a JEI recipe because the salt process is hardcoded and described in the block description, not passing through the recipe list, added one anyway.
