### ISSUE TITLE
Liquid / gas conversion rate problem

### ISSUE THREAD

**Issue by wormzjl** [GlobbyPotato/Rockhounding_Chemistry#40]
So I put 1 bucket of LN2 into the expander and pass the obtained N2 gas into a condenser, in the end I got 15mb of LN2.
I think there might be a problem with the conversion recipe...

**Comment by GlobbyPotato** [comment]
Should be fixed now. Connecting all in a line you expand 1B of LN2 into 70cu of N2 and then condensed into 1B of LN2 again. 
1 vessel should produce 14mb with 0.020cu spare
