### ISSUE TITLE
Crash when using Evaporating Tank

### ISSUE THREAD

**Issue by kave777** [GlobbyPotato/Rockhounding_Chemistry#41]
When I clicked on Evaporating Tank , the world crashes . 
Minecraft version - 1.12.2
Forge version - 14.23.4.2703   
Rockhounding core - 3.11 
Rockhounding Chemistry Mod - 1.12.2-3.15  
here is the crash - https://paste.ee/p/WMmSC
P

**Comment by MineWitherMC** [comment]
This can probably be related to #21 (basically, the same crash message)

**Comment by kave777** [comment]
I clicked with empty hand

**Comment by GlobbyPotato** [comment]
Was the tank empty or at any stage? Did you do any automation on it or used a wrench before? 
The only recognized click is with a shovel when the salt is made. To fix it you can use the Tile Nullifier on it to reset the block and place it again.

**Comment by GlobbyPotato** [comment]
I'm clicking the tank with salt but nothing wrong happens. Probably the block got corrupted someway externally.
For these type of crashes use the Tile Nullifier and it should work again.
