### ISSUE TITLE
Some suggestions, part 3

### ISSUE THREAD

**Issue by wormzjl** [GlobbyPotato/Rockhounding_Chemistry#42]
Hi, I've been playing the mod a bit further and I came up a couple of suggestions mainly regarding automations in this mod:

1. Currently the server can only perform sequantial tasks and cannot be controlled externally, which makes automation of certain tasks difficult. What I have in mind is adding a redstone override, when it receives a redstone signal with certain strgenth, the server will continuously execute tasks in the corresponding file slot. For example, RS strength 1 = slot 1, RS strength 2 = slot 2...RS strength 15 = halt everything.

2. Due to the amount of elements present in this mod, automating all of them manually can be a bit tedious, especially when there are more than one multi-element consumer (alloyers for now) and the material usage is not integer. What I'm suggesting, is adding some sort of element/material pipeline which allows connecting multiple end-users with a central material storage (AE-ish). Althrough unrealstic, this can make the automation process a lot more user-friendly.

3. Add a element/material filter to the lab balance, so instead of extracting everything you can get the stuff you want. Also if you are interested the material pipe, multiple filtered balance connected to such a pipeline can make automation much more enjoyable.

4. I see that there are more than one output on the mineral sizer (green and red..), but the crafttweaker recipe handler shows that it only allow a single output. Is it something that was removed in the old versions? Actually I want to use this device to process regular ores and get some gangues (chance based) as well as the main product. The RS-controlled comminution level is a really interesting mecanism and I'd like to use it to its full extent.

5. A power usage multiplier for machine speed upgrade maybe? Just like the IC2 ones, makes them more balanced.

That's all for now, thank you!

**Comment by GlobbyPotato** [comment]
1. I will consider this later, I planned an update on the server mechanics. I don't remember if there are mods able to produce specific redstone signals, so to have a triggering factor to put in the chain.
2. Sounds interesting but that's something to fit when you'll have many of these users, to see what these users actually and have a pool for test.
3. This has no real utility. The best I can do is to make the balance turnable on/off but you usually want the dust outputted anyway. Would be an unnecessary ticking.
4. The recipe uses an array of possible outputs, each one with a corresponding comminution, what you ask is a crusher with a main output and a separate array of byproduct I guess.
The green slot has a chance to get one if there are more outputs at the same comminution. 
The red slot has a very small chance to get a random one of the entire array.
5. yep we already talked about power multiplier, it's still in progress with also a base multiplier to make by default the machines require more energy.

**Comment by wormzjl** [comment]
Sorry for my bad memory, always forgot what I did in the past -.-
For the crusher, it will be great if you can add a byproduct array.

**Comment by GlobbyPotato** [comment]
The sizer is intended to manipulate the input the way it does, What you ask is a generic crusher and there are already tons of them already.
Sorry, suggestion are considered only if they don't deny the original concepts of the mod.

**Comment by wormzjl** [comment]
Yes, I totally understand that there are plenty of mod does that. But let me explain the difference:

What I'm interested, is associate the side product type/amount with the comminution level, thus the applied redstone strength (or server configuration), just like the unidentified mineral. This will allow a more diversified raw material production as well as imposing more challenge for automations.

For example I'm processing some iron ore, it can produce 2 types of gangues as by-product with  different comminution level (let's say level= 3 and 9). We also have copper ore, which uses level 6 and 10. Thus the one may need to design an automation system which can adjust the level based on the type of input ore if they want to squeeze the last drop of juice out of it.

But anyway it's just a suggestion, don't take it to serious :)

**Comment by GlobbyPotato** [comment]
Ok, it's more clear now the meaning. What you are suggesting is basically the server update I'm already planning. It's for the machines which use the server but don't have a recipe selector to tell which input it is processing, like the sizer or the leaching/retention vat. You should be able to associate an input ingredient to the file. That's the goal I guess.
From the previous message I thought you wanted in example the iron ore producing iron dust by default and a list of byproducts which made me think of the generic crushers.

**Comment by wormzjl** [comment]
Cool, looking forward for the update!
