### ISSUE TITLE
Crash opening existing world

### ISSUE THREAD

**Issue by wormzjl** [GlobbyPotato/Rockhounding_Chemistry#43]
I made a tutorial world some time ago, but after the latest update, it crashes on entering
https://gist.github.com/wormzjl/bca613fa49850e68ba3a63b5e62a8859

**Comment by GlobbyPotato** [comment]
it seems to happen only if there is an hopper under the machine when upgrading.
I made a quick fix that seems to no longer trigger the crash. Should be up soon. Let me know if it fixes. 
If it persists, try downgrading to 3.16, load the world to reset the machine, then upgrade to 3.18.
