### ISSUE TITLE
[1.12.2/3.16] Material Cabinet Overflow

### ISSUE THREAD

**Issue by MineWitherMC** [GlobbyPotato/Rockhounding_Chemistry#44]
![image](https://user-images.githubusercontent.com/18210824/41652614-417e5e7e-748c-11e8-9978-0a9d05be5313.png)
As it can be seen, last 2 materials in each MatCab row overflow into next row. Suprisingly, only one tooltip overflows, hence tooltips and materials do not match. Element Cabinet works perfectly well.

http://codepad.org/UD3kqV8J - script part which adds these materials.

Btw I don't think they should overflow.

**Comment by GlobbyPotato** [comment]
It seems to be a misplacement when composing the gui text and tooltips, The list in the script should be fine. will fix it soon
