### ISSUE TITLE
Adding quanities to Craftweaker Recipes for the Mineral Sizer

### ISSUE THREAD

**Issue by cScotPlay** [GlobbyPotato/Rockhounding_Chemistry#48]
Version
Chemistry 3.19
Core 3.13

Modpack Primal Skies

We are trying to utilize multiple types of charcoal from different mods and allow them to be sized in the Mineral Sizer.  We used craftweaker to add the recipes into the pack.  When viewing the added recipes in JEI it shows the right output and quantities that we scripted.  When the item is actually placed inside of the machine it doesn't seem to recognize the total number from the script for the output.  Below is the actual line in the script.

mods.rockhounding_chemistry.MineralSizer.add(<primal:charcoal_high>, [<rockhounding_chemistry:chemical_items>*3], [2]);

Curious if you had any recommendations for what we might be doing wrong.

**Comment by GlobbyPotato** [comment]
That script actually works for me, I get 3 cracked coal at comminution 2 from the high grade crachoal.
In the script I only added the brackets <> in the primal stack that were missing.

`mods.rockhounding_chemistry.MineralSizer.add(**<primal:charcoal_high>**, [<rockhounding_chemistry:chemical_items>*3], [2]);`

**Comment by cScotPlay** [comment]
Thanks for the quick response and I want to first apologize for not providing more information.  I agree that this script works beautifully by itself.  When added to additional lines for the mineral sizer it only reads the first line in the order.  From what I can initially deduct, it appears that its reading the input item as an ore dict entry even though its written as a specific item.  Below are all of the lines of scripts for the mineral sizer.  It will only read the first line and then replicate that for the rest of the items.  It even adds addtional items to the mineral sizer (i.e. vanilla charcoal).

Version
Craftweaker 4.1.9

//PirmalCore Charcoal
mods.rockhounding_chemistry.MineralSizer.add(<primal:charcoal_high>, [<rockhounding_chemistry:chemical_items>*3], [2]);
mods.rockhounding_chemistry.MineralSizer.add(<primal:charcoal_good>, [<rockhounding_chemistry:chemical_items>*2], [2]);
mods.rockhounding_chemistry.MineralSizer.add(<primal:charcoal_fair>, [<rockhounding_chemistry:chemical_items>], [2]);

**Comment by GlobbyPotato** [comment]
yes, it reads the oredict to group the swappable items with identical characteristics. if you have them registered like "listAllcharcoal" or "listAllcoal" it will read as one. if they have different burntime or characteristics maybe it's not good to group them.

**Comment by cScotPlay** [comment]
Ok got it.  I had to remove the ore dictionary that the PrimalCore mod adds the different coal linking them all together but it now works as expected.  Thanks for the help.  By the way, we are finally getting a fair amount of people to reach Rockhounding Mod: Chemistry and getting really positive response about your mod.

**Comment by GlobbyPotato** [comment]
Thanks, that's a great news!
I've been following the pack because I liked the early game path. Followed the streamers and made several updates/bugfixes from their hints :)
