### ISSUE TITLE
cant fill ampoule from fluid tank

### ISSUE THREAD

**Issue by falizure** [GlobbyPotato/Rockhounding_Chemistry#53]
while trying to setup and automate the retention controller i noticed that the floatation tank sits on top of the 2 sealed vats this poses a problem for automation because the multiblock does not assign a filter to the floatation cell automatically  and wants a ampoule to do so however you can not fill a ampoule with hydrofluoric acid because it is stored in a fluid tank not a pressure vessel or gas holder and you cant set a ampoule from a fluid tank, you also can not use buckets of fluids to set a filter ether, this could pose a problem where you cant filter any fluid block particularly if the multiblock doesnt self assign the filter.

forge version 1.12.2 14.23.4.270
rockhounding chemistry 1.12.2 3.20
rockhounding core 1.12.2 3.13

**Comment by GlobbyPotato** [comment]
To set filters you can pick any fluid or gas from the Fluidpedia using the ampoule.
