### ISSUE TITLE
Crash on new world generation

### ISSUE THREAD

**Issue by MechanosG** [GlobbyPotato/Rockhounding_Chemistry#55]
Just installed the mod.  Loaded up an existing world and everything was fine (probably because of chunks already being generated).  Exited, then tried to disable the Uninspected ore generation (because I plan to spawn it with a different mod) via changing the dimension whitelist from 1 to 999.  This resulted in a crash, and I thought maybe it was because I used too high of a number, or used a dimension ID for a non existent dimension.  So I tried setting it to 1, then set the ore frequency to 0.  But I am still crashing.

Going to set it back to default settings, but set the min level to 239, just to see if this will get a world generating.

Edit:  Forgot to mention, Minecraft 1.12.2, Forge version 14.23.4.2725, Java 8 version 171, using Rockhounding Chemistry 3.20.

Here's the top half of the crash log.
> ---- Minecraft Crash Report ----
> // I blame GlobbyPotato, author of Rockhounding Mod: Chemistry.
> 
> Time: 2018-07-04 23:03:30 PDT
> Description: Exception in server tick loop
> 
> java.lang.ArrayIndexOutOfBoundsException: 1
>     at com.globbypotato.rockhounding_chemistry.world.ChemOresGenerator.generate(ChemOresGenerator.java:25)
>     at net.hycrafthd.worldgenerationprofiler.generation.CustomWorldGenerator.generate(CustomWorldGenerator.java:25)
>     at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:156)
>     at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1018)
>     at net.minecraft.world.chunk.Chunk.populate(Chunk.java:997)
>     at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:157)
>     at net.minecraft.server.MinecraftServer.initialWorldChunkLoad(MinecraftServer.java:344)
>     at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:142)
>     at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:156)
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
>     at java.lang.Thread.run(Unknown Source)

**Comment by GlobbyPotato** [comment]
Did you emptied the config list? Probably It crashed because the list was empty. Try leaving the dimension 0 in the config list and set the frequency to zero. It will not generate anyway.
I will check if I miss the empty check.

**Comment by MechanosG** [comment]
Ok cool.  Will try that.  Setting the dimension to 0 and min level to 239 stopped the crashing for me, but using frequency is probably a better idea.  :+1:
