### ISSUE TITLE
Servers not working

### ISSUE THREAD

**Issue by Fokendov** [GlobbyPotato/Rockhounding_Chemistry#56]
Tried to use the server in the lab oven and it did not work. In the mineral sizer it was okay, but not in the lab oven. Also, the fluid input system and the output don't drop when broken with a pick. Appreciate the attention.

**Comment by GlobbyPotato** [comment]
What version are you using? I think the server not recognizing the oven and dropping of the Fluid System was already fixed.

**Comment by Fokendov** [comment]
Oh yes, I see. In the modpack was not updated. Sorry for the inconvenience. I am currently using 3.09(?)

**Comment by GlobbyPotato** [comment]
no problem. latest is 3.20 with almost all the machines automated by the Server
