### ISSUE TITLE
Fluidpedia and pneumaticcraft 1.12.2

### ISSUE THREAD

**Issue by falizure** [GlobbyPotato/Rockhounding_Chemistry#57]
when using pneumaticcraft repressurized 0.6.8.219 and rockhounding chemistry 3.20 the fluidpedia does not register Gasoline despite showing diesel, kerasine, and lgp that is the only 1 that does not appear in the the fluidpedia as far as i can tell.

**Comment by GlobbyPotato** [comment]
It's there under the F char and not G because it is registered as "fuel".

**Comment by falizure** [comment]
O thank you, i was not expecting that, surprising the number of fluids are under F, it seams all tech reborn fluids also fall under F.

**Comment by GlobbyPotato** [comment]
yep, they added a "fluid" prefix to all, taking all the "F" slots. That will probably force to expand the gui size at some point, not in my list for now.
