### ISSUE TITLE
com.globbypotato.rockhounding_chemistry.handlers.GlobbyEventHandler.onWorldTick() Using a lot of CPU

### ISSUE THREAD

**Issue by wormzjl** [GlobbyPotato/Rockhounding_Chemistry#58]
I've started a server with RH chemistry, but the TPS was pretty low so I checked it with a profiler.
From the profiling result I found that com.globbypotato.rockhounding_chemistry.handlers.GlobbyEventHandler.onWorldTick() is using a lot of cpu time (17% in total) even if players haven't made anything related to RH yet. I have hazard and pollution enabled in config.

![image](https://user-images.githubusercontent.com/2989009/42437076-3314689a-835c-11e8-93d4-dd57dbfdaf33.png)

![image](https://user-images.githubusercontent.com/2989009/42437058-2806c1aa-835c-11e8-8be9-94eb7ac9dc00.png)

Here is the full profiler result if you are interested:
https://sparkprofiler.github.io/?11vRsUXu8m

**Comment by GlobbyPotato** [comment]
Seems to be the toxic mutation process causing this. Probably set something wrong, been trying the way to make it less invasive avoiding the WorldTick. I'll give it a look. 
The entire feature is still in progress, is it so heavy to require an immediate hotfix to disable the feature?

**Comment by wormzjl** [comment]
Yeah when I enabled this I guess that there will be some sort of problem, I'll disable it for now.

**Comment by GlobbyPotato** [comment]
I actually remembered there was a better way of doing this without involving the event. Will test it as I get a free hour and possibly push an hotfix.

**Comment by wormzjl** [comment]
Seems that even with "enable hazard"=false it's still on the profiler with 8% ticktime

**Comment by GlobbyPotato** [comment]
did you tried v3.22. that method is no longer used

**Comment by wormzjl** [comment]
Great, it's no longer on the list
However I haven't tested with pollution enabled, so you might want to take a look at its performance
