### ISSUE TITLE
evaporation tank bucket dupe

### ISSUE THREAD

**Issue by Chromogen** [GlobbyPotato/Rockhounding_Chemistry#6]
rightclicking the tank with a waterbucket will sometimes return another bucket
very rarely it will eat up one

for the random!

**Comment by GlobbyPotato** [comment]
The dupe seems to happen if you right click the tank from the sides. The tank should be interacted only from the top. Should be ok now.

Will upload the update as I can, hopefully fixed the issues,
Sorry about that, the 1.11 changes may hide some traps here and there while reorganizing the code.

**Comment by Chromogen** [comment]
sir, thank you alot for being awsome :)
