### ISSUE TITLE
Powering the Lab Blender with fuel?

### ISSUE THREAD

**Issue by jesmores** [GlobbyPotato/Rockhounding_Chemistry#60]
Does the  lab blender only take RF power? Here's my setup:

Layout
![2018-07-13_09 52 47](https://user-images.githubusercontent.com/125214/42703910-d2147ec0-8682-11e8-994c-5d74f692a495.png)

Power Station
![2018-07-13_09 52 50](https://user-images.githubusercontent.com/125214/42703926-dcf387a0-8682-11e8-9c4b-d55eaf4cb80e.png)

It seems that once the Power Station is oriented against the blender unit, the Redstone Module and RF Generation Mode buttons are locked into place and it won't let me switch back to fuel power.

**Comment by GlobbyPotato** [comment]
Lab blender takes only RF.
Each machine sets on its own what kind of supply it requires from the power station.
This is to make variety between fueled type machines and kind of electrical type machines.
If you have another RF source, attach it to the power station so it will charge from there.

**Comment by jesmores** [comment]
Damn, I don't have any early RF generators that aren't gated behind getting metals from RH:C ore processing.

Does RH:C itself have any options for RF generation? The book seems to hint at syngas, but I'm not sure that also requires some other machines that can only be powered by RF ...

**Comment by jesmores** [comment]
Also it would be nice if the book will mention if a machine can only take certain kind of power. The entry for mineral sizer does mention it can only be powered by fuel, but I didn't see a similar one for the lab blender.

**Comment by GlobbyPotato** [comment]
The mod has the Syngas path for RF. If you track back in JEI you'll find out which machines you need to make it. It should be efficient enough to power the plant for a while.
Put a Gas Turbine in the redstone slot of the power station and hook the syngas on the back of it.

the book tells it in the required component list:
1x Power station (Fuel)
1x Power station (Redstone)
1x Power station (Both)

**Comment by jesmores** [comment]
Oh wow, I'm blind, haha. I was looking in the explanation text and totally missed the components list. Thanks! I'll try to get a Syngas loop running and get back to you.
