### ISSUE TITLE
Catalyst[stupid question]

### ISSUE THREAD

**Issue by Fokendov** [GlobbyPotato/Rockhounding_Chemistry#61]
How do I put the catalyst in the lab oven? Tried just shift clicking or hoppers and it doesn't seem to work. I'm currently playing in version 3.20

**Comment by GlobbyPotato** [comment]
they are recipe ingredients like the compounds in the lab oven. if a recipe uses a catalyst you insert it in its slot after turning the machine on

**Comment by Fokendov** [comment]
Ok. Thaks
