### ISSUE TITLE
Sampling ampoule weirdness

### ISSUE THREAD

**Issue by wormzjl** [GlobbyPotato/Rockhounding_Chemistry#67]
When I opened the gui of a specific pressure vessel, the sample taken in the sampling ampoule in my hotbar become randomly something else.
Other pressure vessels have no such problem through.

**Comment by GlobbyPotato** [comment]
If it's a specific vessel, try breaking it. Maybe it needed a refresh from a version to another. Or craft another ampoule in case it bugged.
Otherwise what was the sample and what was in the vessel? maybe a shared gas with another mod?

**Comment by wormzjl** [comment]
Same after broken & replace... well it's the only one that is bugged.
The gas is random, even from other mods.
I'll keep an eye in case it happened again.

**Comment by GlobbyPotato** [comment]
try using the tile nullifier on that vessel, it will reset it at once, probably it got corrupted

**Comment by wormzjl** [comment]
no new reports, closing for now
