### ISSUE TITLE
Processing speed of Slurry Pond 

### ISSUE THREAD

**Issue by cScotPlay** [GlobbyPotato/Rockhounding_Chemistry#69]
Globby,

Sorry to hit you with two questions but I wanted to separate them for you here. We have noticed that the slurry pond processing speed is relatively slow compared to the rest of the Syngas production system. We noticed that in the newest version it definitely goes processes faster but still falls behind the and appears to be the choke point for the production of Syngas. Both Kiwifrogg and I wanted to get you thoughts on things and open a dialogue about it. Loved to hear your thoughts on the speed and how you see it being utilized.

As always thanks for putting together Chemistry. It has been an absolute blast to play around with.

Scott

**Comment by GlobbyPotato** [comment]
I was pretty sure the speed was never touched. It was set the same as a vanilla furnace, I could be remembering wrong tho.
I just got an idea on how to improve the pond functionality. It should give continuity to the syngas production and give players a strategy choice, still remaining balanced.
But please remember that the slurry pond, like the evaporation tank, are supposed to work in batch. Being a the very beginning of the production chain you need bunches of them working at the same time or you soon will run short. The pond itself cannot be overpowered more than that.

I'll get something done by the weekend, thanks for the hint :)

**Comment by cScotPlay** [comment]
Love the new GUI ans functionality of the Slurry Pond.
