### ISSUE TITLE
Tile Entity Conflict with Mekanism

### ISSUE THREAD

**Issue by MJRLegends** [GlobbyPotato/Rockhounding_Chemistry#7]
Hello, when updating to the new 41 build from 40 build, mekanism doesnt like the fact there is already a tile entity using the same id. see crash log below for more details :P 

https://pastebin.com/zZWyr7dt

Any chance you could add a prefix of like "RockHounding" before it or something? 

MJRLegends

**Comment by GlobbyPotato** [comment]
sure, will change it ASAP, I didn't even know there was already a Laser Amplifier around.

**Comment by MJRLegends** [comment]
@GlobbyPotato Thank you :D
