### ISSUE TITLE
Shibuichi Brick Recipe Crash

### ISSUE THREAD

**Issue by WenXin20** [GlobbyPotato/Rockhounding_Chemistry#71]
Forge v14.23.4.2757-1.12.2
Rockhounding Chemistry v3.27
I got this crash after loading a world.
[Crash Report](https://gist.github.com/WenXin20/6aa804c0d08b30947c55e2a7a8fb27f6)

**Comment by GlobbyPotato** [comment]
I don't get to reproduce this crash. does it happens also using the mod alone or are there removed oredicts or recipes from it?
