### ISSUE TITLE
About the catalyst in Lab Oven

### ISSUE THREAD

**Issue by danikk14g** [GlobbyPotato/Rockhounding_Chemistry#72]
Hello, i am the creator and developer of Craftologia, a tech-modpack backgrounded by chemistry.
Im planning to add Rhodium (Rh) to the modpack, and i found some way to obtain it from Niggliite Shard, Chemical Reactor does not have CT support in the wiki, so i have to use the Lab Oven.
My idea is using Ethanol as main solvent and Sodium Chloride (dust by FrogCraft) instead of a Catalyst to obtain Rhodium Dust from a Niggliite Shard, but i dont know if the recipe is expecting one of the catalysts damageable items in order to work.

Version: 2-3.26

Thanks.

**Comment by GlobbyPotato** [comment]
Hi, yes, the catalyst is meant to be a damageable item. The chemical reactor is from another mod?

**Comment by danikk14g** [comment]
No, its from your mod (Extraction Controller), the machine used to process Niggliite Shard among others.
So i can use a dust in the catalyst slot and it will work just fine?

mods.rockhounding_chemistry.LabOven.add("Rhodium Dust", <rockhounding_chemistry:native_shards:5>, <frogcraftrebirth:intermediate_product:4>, <liquid:ethanol>*1000, null, 
<liquid:toxic_waste>*500, null, <techreborn:dust:63>);

**Comment by GlobbyPotato** [comment]
nope, it doesn't work if the dust is not a damageable item (a sword is a damageable item in example).

the machine is called Chemical Extractor and has CT support
//categoty: the category of the input
//input stack: the item to decompose
//output array: the list of elements oredict composing the input
//quantity array: the list of quantities in PartsPerCraft for each element
mods.rockhounding_chemistry.ChemicalExtractor.add("Sulfate", <minecraft:hardened_clay>, ["dustCalcium", "dustSulfur", "dustCarbon", "dustIron", "dustTin"], [20, 13, 5, 4, 3]);

**Comment by danikk14g** [comment]
Alright thanks for the info, ill create then a damageable container with sodium chloride.
