### ISSUE TITLE
1.12.2 power station wont transmit RF to other modded block

### ISSUE THREAD

**Issue by falizure** [GlobbyPotato/Rockhounding_Chemistry#73]
So the pack im in has Industrial foregoing im trying to start that mod to get a tree farm going for fuel however industrial foregoing in itself doesn't have a starting power generation it relies on RF from some other mods generator to get started, to that end i tried making a power station to power it, set into rf mode and supplied with RF it however would not transfer its RF out ether side into the machines from that mod, i attempted to fudge it by using a leadstone fluxduct from thermal expansion which transfers RF however i could not get it to send power threw the fluxduct as well, it seams that while the power station generates RF it cant seam to output it to other mods objects?

**Comment by GlobbyPotato** [comment]
which version are you using? the redstone module enables the rf generating, the button in the middle turns  the transfering on/off. I tried some machine from tjhe IF mod and seems taking it.

**Comment by GlobbyPotato** [comment]
2K RF was the old threashold to send, it looks like it's till floating around somewhere, will give it a look.
