### ISSUE TITLE
Ore Dictionary / Ingot Priority

### ISSUE THREAD

**Issue by Vyraal1** [GlobbyPotato/Rockhounding_Chemistry#75]
Would it be possible to add in a config where RockHounding won't take priority for smelting materials if a given mod is present? For example if there is thermal foundation, instead of overriding all dustAluminum into Rockhounding's Aluminum, we can specify that `thermalfoundation` should be the modid that takes precedence? And then if there is no other ingot, such as for CuBe, then it will be RockHounding's turn.

**Comment by GlobbyPotato** [comment]
What version is it for? I can make a config to disable the oredict smelting, so my dusts smelt into my ingots leaving other mods smelting on their own. No point in messing with modid, I guess if it's not a mod, it will be the next one in list using the same function to smelt it.

**Comment by Vyraal1** [comment]
Makes sense, this is for the latest version on 1.12.2-3.28

**Comment by wormzjl** [comment]
https://minecraft.curseforge.com/projects/unidict
Try this
