### ISSUE TITLE
Internal Java io issue

### ISSUE THREAD

**Issue by Unerismy** [GlobbyPotato/Rockhounding_Chemistry#77]
This is my first post on here so forgive me if something isnt correct. When i install guidebook the core, and chemistry on my computer, i get internal software problems when trying to connect to my private server. I take these mods off and it connects just fine. I have 3 computers in my house accessing this server, only 1 of them has this issue, and ive tried everything including googling the error that pops and following instructions which included re-installing minecraft, java and disabling firewalls as well as resetting my home router. None of these worked. its a shame because id really like to use this mod. If you need logs or anything let me know and ill provide them

**Comment by GlobbyPotato** [comment]
Hi, since you didn't mentioned them, did you included Bookshelf and RedstoneFlux in the mod folder? They are required too. Eventually, make sure you have the latest version of all of them and all the connected sides have the same identical files, version and config.

**Comment by GlobbyPotato** [comment]
no idea, I see the mod being loaded from the log. By searching for the error it could be some something not matching between the server and the client. You said it happens only on one computer out of 3, so the others are working fine?

**Comment by Unerismy** [comment]
Yea i cant figure it out.  its just the one computer with the exact same mc setup, i copied the .minecraft folder from the computer that it works with exactly and logged into mc with different account, so i know its exactly the same. configs and all. I havent tested the mods individually thoe, like put just the core or guidebook on and see if it does it, you think that would help?

**Comment by GlobbyPotato** [comment]
I can't really tell, there shouldn't be any conflict. You can try posting all the logs so I can see the mod version used. Other than that if the pack is working on a computer and not in another one there can be something not matching.
To be sure it's not my mod, just make a test folder with the mod, the core, guidebook, RF Api and Bookshelf and see if it launches fine. Guidebook creates on launching an additional file called 'gigaherz.commons-1.12.1-0.6.4' so make sure it is generated.

**Comment by Unerismy** [comment]
ok will do. ty very much

**Comment by Unerismy** [comment]
ok i tested all the mods individually and it connects just fine until i put the rockhounding chemistry on. also the gigaherz file is generated

**Comment by Unerismy** [comment]
Ok i finally have news! After lots n lots of testing, i ended up running the server on my computer as it was the only one that didn't have the issue. Used the computer i was running the server on and it has the same problem my other computer was having. So i started the process of elimination, and it seems as if i remove eleccore, deep resonance, and magic bees. (DR and MB rely on Eleccore) i can successfully get both computers to connect! Yay!
