### ISSUE TITLE
suggested feature piping in lava for fuel

### ISSUE THREAD

**Issue by falizure** [GlobbyPotato/Rockhounding_Chemistry#8]
sorry this isn't so much a bug as it is a suggestion but i wasn't sure how to label it as such, anyway point is i recently started playing around with your mod and found it quite unique however their is 1 thing that seamed be missing, i found that your machines appear to be able to have fluids piped in and out by other mods piping as expected, enderio conduits in my current test, i assume items also work but the behavior im interested in would be the ability to pipe lava in as a fuel source, you can already put it in the fuel slot as a bucket, would it be difficult to allow the pumping of liquid fuels such as lava in as well? also sorry if this is a bit of a detour but is geology going to get updated as well? i love the idea of using this mod for both magic and tech.

**Comment by GlobbyPotato** [comment]
Hi, it's ok, suggestions are always welcome! It's a good idea, will try to implement it soon.

As for Gemology, I already started to write it, Maybe it will take some time because it needs to be improved  a lot compared to what the other magic mods do.

**Comment by falizure** [comment]
Thanks :) i am very pleased with how this mod is working out so far and i'm glad to see you so active.
