### ISSUE TITLE
Incorrect information about retention vat in the manual

### ISSUE THREAD

**Issue by wormzjl** [GlobbyPotato/Rockhounding_Chemistry#83]
Edit: There is no problem with the retention vat itself, just the information in the manual is incorrect.
In the following figure there should be HF acid in the first sealed vat
![image](https://user-images.githubusercontent.com/2989009/50518697-3d955300-0ab7-11e9-963d-815429e4b873.png)

In the following figure, the buffer tank should be on the specimen collector instead of second sealed vat.
![image](https://user-images.githubusercontent.com/2989009/50517740-fa84b100-0ab1-11e9-936d-2c95675f5766.png)

**Comment by GlobbyPotato** [comment]
Hi, thanks for noticing it, I indeed used the wrong screenshot with the tank in the wrong slot. Will fix it shortly. 

About the the HF acid I can see it correctly in the game. It should appear like this: 
<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/NFjFBJ6s/hf.png' border='0' alt='hf'/></a>
Are there other versions of the acid in the game? Did you tried to hover the slot where the fluid icon should appear to see if it contains anything?

**Comment by wormzjl** [comment]
Nope, this might be caused by interaction with nuclearcraft, which also added HF acid.

**Comment by GlobbyPotato** [comment]
Probably it means that my mod is not creating a duplicated HF because already created identically by Nuclearcraft "hydrofluoric_acid", hence getting null on the book. I need to see if Guidebook can create fluid from names rather than stacks. In the sealed vat you should see the other HF then in the filter.

**Comment by wormzjl** [comment]
That's true
