### ISSUE TITLE
Extracting Gases to other mods

### ISSUE THREAD

**Issue by Freebi85** [GlobbyPotato/Rockhounding_Chemistry#84]
Hello =)
Well, it's more a question than a issue. Is it possible to extract gases from the system in tanks of other mods? (mekanism gas tanks or fluid tanks) With the Rockhound fluid tank it works well if you use thermal dynamic lines for example. But I can't get gases out somehow. The gas pipelines only connect to mod specific devices. Or maybe I missed something^^

**Comment by GlobbyPotato** [comment]
There is a block called Transposer for this. You need to make a CraftTweaker script for the gases you want to allow to be picked by external mods as a normal fluid. Set input and output the same.

**Comment by Freebi85** [comment]
Thank you very much! just finding the script for it. I will test it tomorrow ;)

**Comment by Freebi85** [comment]
so I did some tests. Importing gases or liquids is no problem =) But exporting gases from a vessel to the transposer only works sometimes when I constantly rotate the device and then it stops immediately. I switched on the gas pump at the exit of the vessel but it does not lead the gas (in my example compressed air) to the transposer.

**Comment by GlobbyPotato** [comment]
To export the gas outside the mod, the input requires a vessel/holder attached to the blue plug with the same orientation, so you send the gas there. I'm afraid the book was missing some info about this particular. Common setups should look like this:
<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/R0KYFGW5/transposer.png' border='0' alt='transposer'/></a>

**Comment by Freebi85** [comment]
It's working! Thank you very much and sorry for the inconvenience. Now I can do crazy things with your mod^^ Great Work Sir!
