### ISSUE TITLE
Slurry Pond is not craftable

### ISSUE THREAD

**Issue by codewarrior0** [GlobbyPotato/Rockhounding_Chemistry#85]
Trailing comma in `assets/rockhounding_chemistry/recipes/slurry_pond.json`:

![image](https://user-images.githubusercontent.com/307683/50624392-e7b01900-0ec3-11e9-94fc-31471ce5404d.png)

`rockhounding_chemistry-1.12.2-3.30.jar`

**Comment by GlobbyPotato** [comment]
oops, thanks, that was an unexpected remaining
