### ISSUE TITLE
Invisible energy buffer for machines

### ISSUE THREAD

**Issue by wormzjl** [GlobbyPotato/Rockhounding_Chemistry#88]
When doing testing, I've always used some creative power sources to power the machines.

I've just found out that after removing the power source, it take a long time before the power and heat gauge in the power station start to decrease, same for the air compressor which doesn't need power station.

So I wonder if there is some sort of hidden power sink within these machines?

**Comment by GlobbyPotato** [comment]
The power station (and the air compressor) has internal reservoirs for lava, syngas and a bit of RF charge, kind of to give immediate buffs for when the bars are filled but going down fast.
You can add 2 buckets of lava, one is immediately turned into yellow bar, the other is consumed once there is enough free burntime.  Same for the 1cu of syngas that will be converted to fuel little by little as there is enough burntime freed.

**Comment by wormzjl** [comment]
Oh, never thought that it can use lava.
Might consider making such reservoir accessible to players?

**Comment by GlobbyPotato** [comment]
Accessible meaning to show a bar of the stored amount? Let's see, that could be too much information for the player, maybe not relievant ones, and extra computing. For a mass working stations are simply meant to go.
For now if you break the station you can see the content of the reservoirs on the item tooltip.

**Comment by wormzjl** [comment]
okay
