### ISSUE TITLE
minor nuisance

### ISSUE THREAD

**Issue by Chromogen** [GlobbyPotato/Rockhounding_Chemistry#9]
the ore in the crusher can be frustrating:
put a hopper underneath: it pulls our the unprocessed ore and the gear aswell as the results
using a filtered modded machine will give problems since ore and results are just metadata difference
blocking the ore and filtring with metadata will still get the gear removed since this one will change metadata

please change something there ;(

**Comment by GlobbyPotato** [comment]
oops my bad, a forgotten value change made all slots extractibe. The hotfix is uploaded.
