### ISSUE TITLE
[Suggestion] Custom catalysts

### ISSUE THREAD

**Issue by wormzjl** [GlobbyPotato/Rockhounding_Chemistry#90]
I was looking at the ethylene oxide process when I realized that I need a silver catalyst.

Currently I believe that the catalyst can be used / regenerated is hardcoded, could you add a ct method to add custom regeneratable catalysts in case people need more than the default ones? 

I was planning to add a damageable item via contenttweaker, and I hope that it doesn't need special handling.

This could be an addition to our last discussion about catalyst regenerator.

**Comment by GlobbyPotato** [comment]
You should be able to add already any custom catalyst to recipes. As long as it is a damageable item, with durability, it will be recognized and also regenerated.

**Comment by wormzjl** [comment]
Oh that's awsome!
