### ISSUE TITLE
[BUG ]Crystal Pulling Crucible doesn't consume melting ingredient when crafting one item.

### ISSUE THREAD

**Issue by WezMakesThings** [GlobbyPotato/Rockhounding_Chemistry#91]
**Issue:**
When the doping(top) ingredient is placed in the pulling crucible one at a time. The melting(bottom ingredient isn't consumed. When placing more than the required doping ingredients the melting ingredient is consumed. Since when placing stacks of each ingredient the process consumes both in the correct ratio I would guess this isn't intended behavior.

**Steps to reproduce:**
-Set up a crystal pulling crucible with the required amount of argon and power.
-Place the required melting ingredient in the chamber.
-Add the doping ingredient to the top.
-Observe as the recipe produces the correct output consumes the doping ingredient but not the melting ingredient.

![2019-02-07_21 23 39](https://user-images.githubusercontent.com/43377122/52455593-c1af1180-2b1e-11e9-89d2-94a93e1ca143.png)
Placed in YAG compound
![2019-02-07_21 23 44](https://user-images.githubusercontent.com/43377122/52455601-c5db2f00-2b1e-11e9-91c3-2f116ffd256c.png)
Place in Neodymium 
![2019-02-07_21 23 47](https://user-images.githubusercontent.com/43377122/52455603-ca9fe300-2b1e-11e9-9b90-dc957abec7be.png)
Processes
![2019-02-07_21 23 50](https://user-images.githubusercontent.com/43377122/52455604-cecc0080-2b1e-11e9-9c4b-df1b808a4176.png)
YAG compound still present.

**Comment by GlobbyPotato** [comment]
Hi, thanks for reporting. There was something missing in the recipe check, will fix it asap.
