### ISSUE TITLE
Suggestion: In-Game Manual

### ISSUE THREAD

**Issue by Danekjovax** [GlobbyPotato/Rockhounding_Chemistry#93]
Subject line sez it all.  Thanks in advance!

**Comment by GlobbyPotato** [comment]
Hi, there is already a manual in the game if you search by mods for "guidebook" in jei (or in the Guidebook creative tab).
There is a "Rockhounding Chemistry Guide Book" with all the info and descriptions about machines and assembling and a "Rockhounding Chemistry Quest Book" for a very step-by-step progression from start to finish.

**Comment by Danekjovax** [comment]
Thanks for the response.  I'll be sure to check again.  I'm playing this mod through freebi85's Dungeons Dragons and Space Shuttles.
