### ISSUE TITLE
Can't find Gas refining tower

### ISSUE THREAD

**Issue by Big-Boofer** [GlobbyPotato/Rockhounding_Chemistry#95]
In Rockhounding Mod: Chemistry 1.12.2-3.39 i can't find the gas refining tower in the game or in jei when using the quest book. it's okay if it isn't in the game.

**Comment by GlobbyPotato** [comment]
HI, in the mod there is not a "Gas Refining", but a "Gas Reforming". It should be this the one you are looking for.
Another tower is the GAN Tower as part of the Cryogenic distillation Plant

**Comment by Big-Boofer** [comment]
Thank Very Much! I love this mod very much also.
