### ISSUE TITLE
Sodium Hydroxide Not Craftable

### ISSUE THREAD

**Issue by FeedCat02** [GlobbyPotato/Rockhounding_Chemistry#99]
In the latest version it seems like sodium hydroxide has a recipe but doesn't show it

**Comment by GlobbyPotato** [comment]
what do you mean? I can see it on the CSTR recipes in JEI.
It is also craftable on the machine, if the input ingredients follow the left-right channel placement.

**Comment by FeedCat02** [comment]
![2019-06-08_08 57 25](https://user-images.githubusercontent.com/45899252/59144186-c059fc80-89cb-11e9-9839-0823ccded30b.png)

**Comment by wormzjl** [comment]
same here

**Comment by GlobbyPotato** [comment]
Oh hang on, it looks like a null check was not in place, so jei removed the recipes later on, tricking my eyes. Should be fixed now. Sorry.
